---
title: "ssf_thesis"
author: "Una Adamoviča"
date: "2025-03-05"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(suncalc)
library(chron)

library(sf)
library(terra)
library(tidyverse)
library(lubridate)
library(corrplot)

library(amt)
library(glmmTMB)

```


```{r workflow}

### collect covariates
# distance to road per class
# land cover: different forest types, open, anthropogenic, water, new forest
# time of day:distance_to_road and time:crossing(y/n)
# season - after decding which models, then build for 3 seasons?
# -- perhaps -- make also the angle analysis = avoidance, attraction, corridor



```



```{r preperation of moose data, echo=TRUE}

moose <- read.csv("moose_df.csv")

# clean and make tracks 
moose <- moose %>% 
  mutate(timestamp = as.POSIXct(as.character(timestamp),  format = "%Y-%m-%d %H:%M:%S")) %>%
  filter(!is.na(timestamp)) %>% 
  make_track(UTM.Easting, UTM.Northing, timestamp, crs = 3301, id = id)

head(moose, 5)

# # A tibble: 5 × 4
#        x_       y_ t_                     id
# *   <dbl>    <dbl> <dttm>              <int>
# 1 591225. 6545176. 2018-11-23 22:30:18 39789
# 2 591250. 6545167. 2018-11-23 23:00:08 39789
# 3 591337. 6545008. 2018-11-23 23:30:16 39789
# 4 591292. 6544921. 2018-11-24 00:00:11 39789
# 5 591238. 6545135. 2018-11-24 00:30:30 39789

summarize_sampling_rate_many(moose, "id")

# make manipulations of moose data
moose_sf <- st_as_sf(moose, coords = c("x_", "y_"), crs = 3301) 

# create lines
moose_lines <- moose_sf %>%
  group_by(id) %>%
  summarize(do_union = FALSE) %>%
  st_cast("LINESTRING")
plot(moose_lines)

# create study area to clip everyhting
study_area <- moose_sf %>%
  st_buffer(dist = 1823) %>%
  st_union() %>%
  st_as_sf()

saveRDS(study_area, "study_area.rds")

# remove the points when animals are resting
points_to_keep <- moose_sf %>%
  group_by(id) %>%
  mutate(
    distance = as.numeric(st_distance(geometry, lead(geometry), by_element = TRUE)),
    keep_point = !is.na(distance) & distance > 18
  ) %>%
  pull(keep_point)

moose_filter <- moose[points_to_keep, ]
head(moose_filter, 5)

# > head(moose_filter, 5)
# # A tibble: 5 × 4
#        x_       y_ t_                     id
# *   <dbl>    <dbl> <dttm>              <int>
# 1 591225. 6545176. 2018-11-23 22:30:18 39789
# 2 591250. 6545167. 2018-11-23 23:00:08 39789
# 3 591337. 6545008. 2018-11-23 23:30:16 39789
# 4 591292. 6544921. 2018-11-24 00:00:11 39789
# 5 591238. 6545131. 2018-11-24 03:00:15 39789

# list-column to make it easy to apply functions to each animal data seperately 
dat1 <- moose_filter %>% nest(data = -id)
head(dat1,8)

# > head(dat1,8)
# # A tibble: 8 × 2
#      id data                  
#   <int> <list>                
# 1 39789 <trck_xyt [4,548 × 3]>
# 2 39787 <trck_xyt [6,073 × 3]>
# 3 39785 <trck_xyt [5,870 × 3]>
# 4 39788 <trck_xyt [5,140 × 3]>
# 5 39793 <trck_xyt [5,894 × 3]>
# 6 39791 <trck_xyt [5,780 × 3]>
# 7 39790 <trck_xyt [5,464 × 3]>
# 8 39794 <trck_xyt [6,430 × 3]>

# resample to have everything consistent
dat2 <- dat1 %>% 
  mutate(dat.resample = map(data, ~ track_resample(., 
                                                   rate = lubridate::minutes(30), 
                                                   tolerance = lubridate::minutes(4)))) 

head(dat2)

# id
# <int>
# data
# <list>
# dat.resample
# <list>
# 39789	<S3: track_xyt>	<S3: track_xyt>		
# 39787	<S3: track_xyt>	<S3: track_xyt>		
# 39785	<S3: track_xyt>	<S3: track_xyt>		
# 39788	<S3: track_xyt>	<S3: track_xyt>		
# 39793	<S3: track_xyt>	<S3: track_xyt>		
# 39791	<S3: track_xyt>	<S3: track_xyt>	

# ----------- sample period ------------

# sample period for each moose
time_summary <- moose %>%
  group_by(id) %>%
  summarize(
    start_date = format(min(t_), "%Y/%m/%d"),
    end_date = format(max(t_), "%Y/%m/%d"),
    sample_period = paste(start_date, "–", end_date)
  )

total_steps <- moose %>%
  group_by(id) %>%
  summarize(actual_steps = n())

active_steps <- moose_filter %>%
  group_by(id) %>%
  summarize(active_steps = n())

# combine all information
result_table <- time_summary %>%
  left_join(total_steps, by = "id") %>%
  left_join(active_steps, by = "id") %>%
  mutate(
    inactive_steps = actual_steps - active_steps,
  ) %>%
  dplyr::select(id, sample_period, actual_steps, active_steps, inactive_steps)

formatted_table <- result_table %>%
  rename(`Individual Id` = id,
         `Sample Period` = sample_period,
         `Number of actual steps` = actual_steps,
         `Number of active steps` = active_steps,
         `Number of inactive steps` = inactive_steps)

formatted_table


```


```{r collecting covariates}
#layers

new_forest <- rast("D:\\Users\\amand\\Documents\\qgis\\masters_data\\Hansen_GFC-2022-v1.10_lossyear_60N_020E.tif")

roads <- st_read("D:\\Users\\amand\\Documents\\qgis\\masters_qgis\\vectors\\full-road-classes.gpkg")

corine <- rast("D:\\Users\\amand\\Documents\\qgis\\masters_qgis\\rasters\\corine_30m_resample_mode.tif")

slope <- rast("D:\\Users\\amand\\Documents\\qgis\\masters_qgis\\rasters\\slope_30m_degrees.tif")

study_area <- readRDS("study_area.rds")

#### 1. landuse
# reclassify matrix to group landuse categories
m <- matrix(c(0,22,1,
              22,23, 2,
              23, 24, 3,
              24, 25, 4,
              25, 41, 5), ncol = 3, byrow = TRUE)

# 1 = human-modified = agriculture and anthropogenic
# 2 = broad-leaved (deciduous)
# 3 = coniferous
# 4 = mixed
# 5 = open areas -> combine with srub and peatbog and water
# lowest excluded, maximum included

landuse <- terra::classify(corine, m) %>%
  crop(study_area) %>% 
  mask(study_area) %>% 
  setNames("landuse")

#### 2. roads + distance
# distance to roads code
  # mutate(
  #   nearest_major = st_distance(geometry,st_union(roads[roads$class>= 2, ])),
  #   nearest_minor = st_distance(geometry, st_union(roads[roads$class== 1, ])),
  #   nearest_local = st_distance(geometry, st_union(roads[roads$class == 0, ]))
  # )


major_roads_dist <- roads[roads$class ==3,] %>%
  rasterize(landuse) %>%
  distance() %>% 
  crop(study_area) %>% 
  mask(study_area) %>% 
  setNames("major_d")

minor_roads_dist <- roads[roads$kal > 100 & roads$kal < 4500,] %>%
  rasterize(landuse) %>%
  distance() %>% 
  crop(study_area) %>% 
  mask(study_area) %>% 
  setNames("minor_d")

local_roads_dist <- roads[roads$kal <= 100 | roads$class == 0,] %>%
  rasterize(landuse) %>%
  distance() %>% 
  crop(study_area) %>% 
  setNames("local_d")

state_roads_dist <- roads[roads$kal > 100,] %>%
  rasterize(landuse) %>%
  distance() %>% 
  crop(study_area) %>% 
  mask(study_area) %>% 
  setNames("state_d")

# > max(local_roads_dist[], na.rm = TRUE)
# [1] 2400.75
# > max(state_roads_dist[], na.rm = TRUE)
# [1] 7417.344
# > 
# > # Get the mean distance value across the entire study area
# > mean(local_roads_dist[], na.rm = TRUE)
# [1] 386.3964
# > mean(state_roads_dist[], na.rm = TRUE)
# [1] 2102.572


#### 3. new forest (forest loss)
# reproject the layer, align the grids, and assign binary values to have new forest y/n
new_forest <- new_forest %>% 
  project(landuse) %>% 
  resample(landuse, method = "near") %>% 
  classify(matrix(c(3, 16, 1,
                    16, 22, 0), ncol = 3, byrow = TRUE)) %>% 
  crop(study_area) %>% 
  mask(study_area) %>% 
  setNames("new_forest")

# where new forest is 
mask_new_forest <- new_forest == 1

landuse_in_newforest <- mask(landuse, mask_new_forest)

freq_table <- terra::freq(landuse_in_newforest)
total_pixels <- sum(freq_table$count, na.rm = TRUE)
freq_table$percentage <- (freq_table$count / total_pixels) * 100

# > freq_table
#   layer value  count percentage
# 1     1     1 123684  24.021255
# 2     1     2  11752   2.282412
# 3     1     3 126907  24.647209
# 4     1     4 130521  25.349101
# 5     1     5 122030  23.700024

# where forest is in landuse
forest_types <- landuse %in% c(2, 3, 4, 5)
forest_to_override <- forest_types & mask_new_forest

landuse_total <- landuse %>% 
  setNames("landuse_total")
landuse_total[forest_to_override] <- 6

freq_before <- terra::freq(landuse)
freq_after <- terra::freq(landuse_total)
print(data.frame(
  Category = c("Human-modified", "Deciduous", "Coniferous", "Mixed", "Open/shrub/bog", "New forest"),
  Before = c(freq_before$count, 0),  # Add 0 for the new category that didn't exist before
  After = freq_after$count
))

#### 4. slope

slope <- slope %>%
  crop(study_area) %>% 
  mask(study_area) %>% 
  setNames("slope")



```


```{r all moose}

# # remove for each moose if burst < 3
# dat3 <- dat2 %>%
#   mutate(dat.filtered = map(dat.resample, ~ filter_min_n_burst(., min_n = 3)))
# # try to retain the filtered AND the id columns
# all_moose <- map2_dfr(dat3$dat.filtered, dat3$id, ~{
#   .x %>% mutate(id = .y)
# })
# # again it wants to remove the id, so make map
# burst_id_map <- as.data.frame(all_moose) %>%
#   dplyr::select(id, burst_) %>%
#   distinct()
# 
# saveRDS(burst_id_map, "burst_id_map.rds")

# --------------------------------------- DO NOT TOUCH OR RUN THIS --------------------------

# set.seed(456) 
# # regular generation of steps
# steps <- all_moose %>%
#   steps_by_burst() %>%
#   random_steps(n_control = 10, 
#               sl_distr = fit_distr(.$sl_, "gamma"),
#               ta_distr = fit_distr(.$ta_, "vonmises"), 
#               include_observed = TRUE) %>% 
#   remove_incomplete_strata()
# 
# 
# saveRDS(steps, "steps_data_fixed.rds")
# 



# ----------------------------------------------------------------- start working only from HERE --------------


# steps <- readRDS("steps_data_fixed.rds")
# 
# 
# # try to join back the moose id to have for glmmm as random effect
# steps <- steps %>%
#   left_join(burst_id_map, by = "burst_", relationship = "many-to-one", multiple = "first")

steps <- readRDS("steps_data_fixed_with_burst.rds")


# get the covariates for each step
steps2 <- steps %>% 
  extract_covariates(landuse_total) %>% 
  extract_covariates(major_roads_dist) %>%
  extract_covariates(minor_roads_dist) %>%
  extract_covariates(local_roads_dist) %>% 
  extract_covariates(slope)


#  time categories
steps2 <- steps2 %>%
  mutate(
    time_of_day = chron(times = format(t1_, format = "%H:%M:%S")),
    date = as.Date(t1_, format = "%Y/%m/%d")
  ) 

saveRDS(steps2, "steps2.rds")


# get time of day times to assign time categories
sunlight <- getSunlightTimes(
  date = steps2$date,
  lon = 25.45, 
  lat = 59.05, 
  keep = c("sunrise", "sunset", "dawn", "dusk"),
  tz = "Europe/Tallinn"
)

steps3 <- steps2 %>%
  # join to get the time of sunglight for each observation
  left_join(sunlight, by = "date", relationship = "many-to-many", multiple = "first") %>%
  
  # assign time category for each observation based on sunlight availability
  mutate(
    sunrise = chron(times = format(sunrise, format = "%H:%M:%S")),
    sunset = chron(times = format(sunset, format = "%H:%M:%S")),
    dawn = chron(times = format(dawn, format = "%H:%M:%S")),
    dusk = chron(times = format(dusk, format = "%H:%M:%S")),
    
    time_category = case_when(
      time_of_day >= sunrise & time_of_day < sunset ~ "Day", # day
      (time_of_day >= dawn & time_of_day < sunrise) | 
        (time_of_day >= sunset & time_of_day < dusk) ~ "Twilight", # twilight
      TRUE ~ "Night"), #night
    
    month = lubridate::month(t1_, label = TRUE),
    
    # assign season category
    season = case_when(
      (date >= as.Date("2018-11-23") & date <= as.Date("2019-04-06")) ~ "Winter",
      (date >= as.Date("2019-04-07") & date <= as.Date("2019-05-31")) ~ "Spring",
      (date >= as.Date("2019-06-01") & date <= as.Date("2019-09-02")) ~ "Summer"
    ),
    
    # insert state road distances (major + minor class) 
    state_d = pmin(minor_d, major_d, na.rm = TRUE)

  ) %>%
  
  # remove some unnecessary attributes
  dplyr::select(-sunrise, -sunset, -dawn, -dusk, -lon, -lat)


# steffanie suggestion how to structure data for injection
d.map <- data.frame(step_id_=unique(steps3$step_id_), 
                    str_ID=1:length(unique(steps3$step_id_)))

# put new sequential stratum ID
steps3$str_ID <- d.map[match(steps3$step_id_, d.map$step_id_), "str_ID"]

# ordering data by stratum id
steps3 <- steps3[order(steps3$str_ID),]

# give meaningful names and give reference category
steps3$landuse_factor <- factor(steps3$landuse_total,
                                labels = c("Human-modified", "Deciduous",
                                           "Coniferous", "Mixed", "Open/shrub/bog", "New forest")) %>% 
  relevel(ref = "Coniferous")

# 1 = human-modified = agriculture and anthropogenic
# 2 = broad-leaved (deciduous)
# 3 = coniferous
# 4 = mixed
# 5 = open areas -> combine with shrub and peatbog and water
# 6 = new forest 

# change reference category
steps3$time_category <- factor(steps3$time_category) %>% relevel(ref = "Day")
steps3$season <- factor(steps3$season) %>% relevel(ref = "Winter")

# create an original (before scaling) variable
steps3_original <- steps3

steps3$s_sl_ <- scale(steps3$sl_)
steps3$s_ta_ <- scale(cos(steps3$ta_))
steps3$s_minor_d <- scale(steps3$minor_d)
steps3$s_major_d <- scale(steps3$major_d)
steps3$s_local_d <- scale(steps3$local_d)
steps3$s_state_d <- scale(steps3$state_d)
steps3$s_slope <- scale(steps3$slope)

steps3$num_case_ <- as.numeric(steps3$case_)

```



```{r base movement model}


#----------------------------------------------------- glmm ----------------------------------------------------

# Define GLMM structure without fitting
TMBStruc1 <- glmmTMB(
  num_case_ ~ s_sl_ + s_ta_ + s_slope +
    s_minor_d + s_major_d + s_local_d + 
    landuse_factor +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

# put variance 1e3, so SD would be 1e6
TMBStruc1$parameters$theta[1] = log(1e3)  

# assign that the variance would not be estimated for the first random effect 
TMBStruc1$mapArg = list(theta = factor(c(NA, 1)))

# now finally fit the model
model_glmm1 <- glmmTMB:::fitTMB(TMBStruc1)

summary(model_glmm1)

saveRDS(model_glmm1, "model_glmm1.rds")
#       AIC       BIC    logLik  deviance  df.resid 
#  405766.9  405900.6 -202870.4  405740.9    216962 

#                               Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                  -3.068020   7.123379  -0.431  0.66669    
# s_sl_                         0.135530   0.006661  20.348  < 2e-16 ***
# s_ta_                         0.006911   0.007514   0.920  0.35773    
# s_slope                      -0.010967   0.009679  -1.133  0.25718    
# s_minor_d                     0.258421   0.087759   2.945  0.00323 ** 
# s_major_d                     0.155094   0.092519   1.676  0.09367 .  
# s_local_d                     0.086606   0.022225   3.897 9.75e-05 ***
# landuse_factorHuman-modified -0.302504   0.046171  -6.552 5.69e-11 ***
# landuse_factorDeciduous       0.265583   0.053662   4.949 7.45e-07 ***
# landuse_factorMixed           0.066082   0.032755   2.017  0.04365 *  
# landuse_factorOpen/shrub/bog  0.058928   0.038842   1.517  0.12923    
# landuse_factorNew forest      0.373752   0.027322  13.679  < 2e-16 ***


# ---- basic with 2 road categories -------

TMBStruc1.1 <- glmmTMB(
  num_case_ ~ s_sl_ + s_ta_ +
    s_state_d + s_local_d + s_slope +
    landuse_factor +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc1.1$parameters$theta[1] = log(1e3)  
TMBStruc1.1$mapArg = list(theta = factor(c(NA, 1)))
model_glmm1.1 <- glmmTMB:::fitTMB(TMBStruc1.1)
summary(model_glmm1.1)

saveRDS(model_glmm1.1, "model_glmm1.1.rds")

#       AIC       BIC    logLik  deviance  df.resid 
#  405751.8  405875.2 -202863.9  405727.8    216963 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.471e-01    0.3836
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                               Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                  -3.071685   7.123302  -0.431 0.666311    
# s_sl_                         0.135458   0.006669  20.311  < 2e-16 ***
# s_ta_                         0.007171   0.007516   0.954 0.340005    
# s_state_d                     0.401864   0.076845   5.230 1.70e-07 ***
# s_local_d                     0.075211   0.022237   3.382 0.000719 ***
# s_slope                      -0.010515   0.009678  -1.086 0.277306    
# landuse_factorHuman-modified -0.300789   0.046147  -6.518 7.12e-11 ***
# landuse_factorDeciduous       0.266532   0.053649   4.968 6.76e-07 ***
# landuse_factorMixed           0.069606   0.032762   2.125 0.033622 *  
# landuse_factorOpen/shrub/bog  0.060784   0.038823   1.566 0.117428    
# landuse_factorNew forest      0.377748   0.027334  13.820  < 2e-16 ***

# ----------------------------------------- basic with 2 road categories -1 -------------------------

# remove ta_
TMBStruc1.1.1 <- glmmTMB(
  num_case_ ~ s_sl_ +
    s_state_d + s_local_d + s_slope +
    landuse_factor +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc1.1.1$parameters$theta[1] = log(1e3)  
TMBStruc1.1.1$mapArg = list(theta = factor(c(NA, 1)))
model_glmm1.1.1 <- glmmTMB:::fitTMB(TMBStruc1.1.1)
summary(model_glmm1.1.1)

saveRDS(model_glmm1.1.1, "model_glmm1.1.1.rds")

#       AIC       BIC    logLik  deviance  df.resid 
#  405750.7  405863.9 -202864.4  405728.7    216964 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.504e-01    0.3878
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                               Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                  -3.069803   7.123382  -0.431 0.666507    
# s_sl_                         0.135573   0.006668  20.331  < 2e-16 ***
# s_state_d                     0.400414   0.076772   5.216 1.83e-07 ***
# s_local_d                     0.074520   0.022210   3.355 0.000793 ***
# s_slope                      -0.010405   0.009675  -1.075 0.282171    
# landuse_factorHuman-modified -0.299346   0.046106  -6.493 8.44e-11 ***
# landuse_factorDeciduous       0.266779   0.053635   4.974 6.56e-07 ***
# landuse_factorMixed           0.069763   0.032753   2.130 0.033175 *  
# landuse_factorOpen/shrub/bog  0.061151   0.038810   1.576 0.115101    
# landuse_factorNew forest      0.377913   0.027328  13.829  < 2e-16 ***
--- 


# remove slope
TMBStruc1.1.2 <- glmmTMB(
  num_case_ ~  s_sl_ +
    s_state_d + s_local_d +
    landuse_factor +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc1.1.2$parameters$theta[1] = log(1e3)  
TMBStruc1.1.2$mapArg = list(theta = factor(c(NA, 1)))
model_glmm1.1.2 <- glmmTMB:::fitTMB(TMBStruc1.1.2)
summary(model_glmm1.1.2)

saveRDS(model_glmm1.1.2, "model_glmm1.1.2.rds")


#       AIC       BIC    logLik  deviance  df.resid 
#  405749.9  405852.7 -202864.9  405729.9    216965 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance Std.Dev. 
#  str_ID (Intercept) 1.00e+06 1000.0000
#  id     (Intercept) 1.51e-01    0.3886
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                               Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                  -3.064139   7.123372  -0.430 0.667084    
# s_sl_                         0.135522   0.006668  20.324  < 2e-16 ***
# s_state_d                     0.402493   0.076747   5.244 1.57e-07 ***
# s_local_d                     0.076248   0.022151   3.442 0.000577 ***
# landuse_factorHuman-modified -0.304175   0.045889  -6.628 3.39e-11 ***
# landuse_factorDeciduous       0.264726   0.053602   4.939 7.86e-07 ***
# landuse_factorMixed           0.068536   0.032733   2.094 0.036281 *  
# landuse_factorOpen/shrub/bog  0.060289   0.038801   1.554 0.120229    
# landuse_factorNew forest      0.376229   0.027284  13.789  < 2e-16 ***


# --- landuse local -----

TMBStruc_local <- glmmTMB(
  num_case_ ~ s_sl_ + s_ta_ + s_slope +
    s_local_d +
    landuse_factor + landuse_factor:s_local_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

saveRDS(model_glmm1.1, "model_glmm1.1.rds")
TMBStruc_local$parameters$theta[1] = log(1e3)  
TMBStruc_local$mapArg = list(theta = factor(c(NA, 1)))
model_glmm_local <- glmmTMB:::fitTMB(TMBStruc_local)
summary(model_glmm_local)

saveRDS(model_glmm_local, "model_glmm_local.rds")


#       AIC       BIC    logLik  deviance  df.resid 
#  405770.4  405935.0 -202869.2  405738.4    216959 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.493e-01    0.3865
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                                          Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                            -3.060e+00  7.123e+00  -0.430 0.667485    
# s_sl_                                   1.364e-01  6.661e-03  20.477  < 2e-16 ***
# s_ta_                                   6.675e-03  7.513e-03   0.888 0.374286    
# s_slope                                -1.172e-02  9.676e-03  -1.211 0.225753    
# s_local_d                               6.399e-02  2.852e-02   2.244 0.024863 *  
# landuse_factorHuman-modified           -2.357e-01  7.185e-02  -3.280 0.001037 ** 
# landuse_factorDeciduous                 1.944e-01  5.816e-02   3.343 0.000827 ***
# landuse_factorMixed                     6.197e-02  3.321e-02   1.866 0.062010 .  
# landuse_factorOpen/shrub/bog            5.628e-02  3.943e-02   1.427 0.153478    
# landuse_factorNew forest                3.654e-01  2.758e-02  13.248  < 2e-16 ***
# s_local_d:landuse_factorHuman-modified  1.314e-01  7.510e-02   1.750 0.080180 .  
# s_local_d:landuse_factorDeciduous       1.517e-01  5.115e-02   2.965 0.003025 ** 
# s_local_d:landuse_factorMixed           6.199e-02  3.324e-02   1.865 0.062184 .  
# s_local_d:landuse_factorOpen/shrub/bog -1.316e-02  3.251e-02  -0.405 0.685712    
# s_local_d:landuse_factorNew forest     -1.521e-05  2.806e-02  -0.001 0.999568  



# remove ta_ significant 

TMBStruc_local.1 <- glmmTMB(
  num_case_ ~ s_sl_ + s_slope +
    s_local_d +
    landuse_factor + landuse_factor:s_local_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc_local.1$parameters$theta[1] = log(1e3)  
TMBStruc_local.1$mapArg = list(theta = factor(c(NA, 1)))
model_glmm_local.1 <- glmmTMB:::fitTMB(TMBStruc_local.1)
summary(model_glmm_local.1)
saveRDS(model_glmm_local.1, "model_glmm_local.1.rds")


#       AIC       BIC    logLik  deviance  df.resid 
#  405769.2  405923.5 -202869.6  405739.2    216960 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.448e-01    0.3805
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                                          Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                            -3.061e+00  7.123e+00  -0.430 0.667433    
# s_sl_                                   1.365e-01  6.661e-03  20.496  < 2e-16 ***
# s_slope                                -1.161e-02  9.673e-03  -1.200 0.230164    
# s_local_d                               6.335e-02  2.850e-02   2.223 0.026225 *  
# landuse_factorHuman-modified           -2.346e-01  7.182e-02  -3.267 0.001088 ** 
# landuse_factorDeciduous                 1.947e-01  5.814e-02   3.349 0.000811 ***
# landuse_factorMixed                     6.213e-02  3.320e-02   1.872 0.061272 .  
# landuse_factorOpen/shrub/bog            5.661e-02  3.942e-02   1.436 0.150960    
# landuse_factorNew forest                3.655e-01  2.757e-02  13.256  < 2e-16 ***
# s_local_d:landuse_factorHuman-modified  1.310e-01  7.507e-02   1.745 0.081061 .  
# s_local_d:landuse_factorDeciduous       1.516e-01  5.114e-02   2.965 0.003028 ** 
# s_local_d:landuse_factorMixed           6.188e-02  3.323e-02   1.862 0.062603 .  
# s_local_d:landuse_factorOpen/shrub/bog -1.309e-02  3.250e-02  -0.403 0.687202    
# s_local_d:landuse_factorNew forest     -8.502e-05  2.806e-02  -0.003 0.997582    

# remove slope  

TMBStruc_local.2 <- glmmTMB(
  num_case_ ~ s_sl_ +
    s_local_d +
    landuse_factor + landuse_factor:s_local_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc_local.2$parameters$theta[1] = log(1e3)  
TMBStruc_local.2$mapArg = list(theta = factor(c(NA, 1)))
model_glmm_local.2 <- glmmTMB:::fitTMB(TMBStruc_local.2)
summary(model_glmm_local.2)
saveRDS(model_glmm_local.2, "model_glmm_local.2.rds")


#       AIC       BIC    logLik  deviance  df.resid 
#  405768.6  405912.6 -202870.3  405740.6    216961 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.441e-01    0.3796
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                                          Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                            -3.0600736  7.1232315  -0.430 0.667493    
# s_sl_                                   0.1364440  0.0066600  20.487  < 2e-16 ***
# s_local_d                               0.0653395  0.0284483   2.297 0.021631 *  
# landuse_factorHuman-modified           -0.2396922  0.0716549  -3.345 0.000823 ***
# landuse_factorDeciduous                 0.1925738  0.0581169   3.314 0.000921 ***
# landuse_factorMixed                     0.0608456  0.0331817   1.834 0.066697 .  
# landuse_factorOpen/shrub/bog            0.0556832  0.0394121   1.413 0.157701    
# landuse_factorNew forest                0.3636295  0.0275284  13.209  < 2e-16 ***
# s_local_d:landuse_factorHuman-modified  0.1314330  0.0750366   1.752 0.079845 .  
# s_local_d:landuse_factorDeciduous       0.1510719  0.0511419   2.954 0.003137 ** 
# s_local_d:landuse_factorMixed           0.0622137  0.0332238   1.873 0.061129 .  
# s_local_d:landuse_factorOpen/shrub/bog -0.0131094  0.0324991  -0.403 0.686670    
# s_local_d:landuse_factorNew forest     -0.0002223  0.0280526  -0.008 0.993678  


# ---- landuse state -----

TMBStruc_state<- glmmTMB(
  num_case_ ~ s_sl_ + s_ta_ + s_slope +
    s_state_d +
    landuse_factor + landuse_factor:s_state_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc_state$parameters$theta[1] = log(1e3)  
TMBStruc_state$mapArg = list(theta = factor(c(NA, 1)))
model_glmm_state <- glmmTMB:::fitTMB(TMBStruc_state)
summary(model_glmm_state)

saveRDS(model_glmm_state, "model_glmm_state.rds")


#       AIC       BIC    logLik  deviance  df.resid 
#  405702.2  405866.8 -202835.1  405670.2    216959 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.474e-01    0.3839
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                                         Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                            -3.077922   7.123305  -0.432  0.66567    
# s_sl_                                   0.137405   0.006677  20.580  < 2e-16 ***
# s_ta_                                   0.006878   0.007513   0.915  0.35993    
# s_slope                                -0.010395   0.009670  -1.075  0.28235    
# s_state_d                               0.368754   0.079314   4.649 3.33e-06 ***
# landuse_factorHuman-modified           -0.306603   0.046443  -6.602 4.06e-11 ***
# landuse_factorDeciduous                 0.339015   0.058831   5.762 8.29e-09 ***
# landuse_factorMixed                     0.066229   0.033053   2.004  0.04510 *  
# landuse_factorOpen/shrub/bog            0.072814   0.039372   1.849  0.06441 .  
# landuse_factorNew forest                0.371223   0.027494  13.502  < 2e-16 ***
# s_state_d:landuse_factorHuman-modified  0.232146   0.041981   5.530 3.21e-08 ***
# s_state_d:landuse_factorDeciduous       0.229146   0.078063   2.935  0.00333 ** 
# s_state_d:landuse_factorMixed          -0.063376   0.032796  -1.932  0.05331 .  
# s_state_d:landuse_factorOpen/shrub/bog -0.038827   0.038113  -1.019  0.30833    
# s_state_d:landuse_factorNew forest      0.017778   0.028997   0.613  0.53982  
# remove non significant ta_ parameter


TMBStruc_state.1<- glmmTMB(
  num_case_ ~  s_sl_  + s_slope +
    s_state_d +
    landuse_factor + landuse_factor:s_state_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc_state.1$parameters$theta[1] = log(1e3)  
TMBStruc_state.1$mapArg = list(theta = factor(c(NA, 1)))
model_glmm_state.1 <- glmmTMB:::fitTMB(TMBStruc_state.1)
summary(model_glmm_state.1)

saveRDS(model_glmm_state.1, "model_glmm_state.1.rds")

#       AIC       BIC    logLik  deviance  df.resid 
#  405701.1  405855.4 -202835.5  405671.1    216960 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.486e-01    0.3855
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                                         Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                            -3.066156   7.123344  -0.430  0.66688    
# s_sl_                                   0.137518   0.006676  20.600  < 2e-16 ***
# s_slope                                -0.010265   0.009666  -1.062  0.28827    
# s_state_d                               0.367245   0.079241   4.635 3.58e-06 ***
# landuse_factorHuman-modified           -0.305116   0.046398  -6.576 4.83e-11 ***
# landuse_factorDeciduous                 0.339323   0.058816   5.769 7.96e-09 ***
# landuse_factorMixed                     0.066413   0.033044   2.010  0.04445 *  
# landuse_factorOpen/shrub/bog            0.073103   0.039360   1.857  0.06327 .  
# landuse_factorNew forest                0.371361   0.027488  13.510  < 2e-16 ***
# s_state_d:landuse_factorHuman-modified  0.231712   0.041963   5.522 3.36e-08 ***
# s_state_d:landuse_factorDeciduous       0.229212   0.078048   2.937  0.00332 ** 
# s_state_d:landuse_factorMixed          -0.063431   0.032789  -1.935  0.05305 .  
# s_state_d:landuse_factorOpen/shrub/bog -0.038791   0.038101  -1.018  0.30862    
# s_state_d:landuse_factorNew forest      0.017782   0.028992   0.613  0.53964  

# remove slope parameter


TMBStruc_state.2<- glmmTMB(
  num_case_ ~ s_sl_  +
    s_state_d +
    landuse_factor + landuse_factor:s_state_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc_state.2$parameters$theta[1] = log(1e3)  
TMBStruc_state.2$mapArg = list(theta = factor(c(NA, 1)))
model_glmm_state.2 <- glmmTMB:::fitTMB(TMBStruc_state.2)
summary(model_glmm_state.2)
saveRDS(model_glmm_state.2, "model_glmm_state.2.rds")


#       AIC       BIC    logLik  deviance  df.resid 
#  405700.2  405844.2 -202836.1  405672.2    216961 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance Std.Dev. 
#  str_ID (Intercept) 1.00e+06 1000.0000
#  id     (Intercept) 1.49e-01    0.3861
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                                         Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                            -3.070353   7.123345  -0.431  0.66645    
# s_sl_                                   0.137461   0.006675  20.593  < 2e-16 ***
# s_state_d                               0.369797   0.079203   4.669 3.03e-06 ***
# landuse_factorHuman-modified           -0.309985   0.046173  -6.713 1.90e-11 ***
# landuse_factorDeciduous                 0.336595   0.058764   5.728 1.02e-08 ***
# landuse_factorMixed                     0.065283   0.033027   1.977  0.04808 *  
# landuse_factorOpen/shrub/bog            0.072472   0.039354   1.842  0.06554 .  
# landuse_factorNew forest                0.369786   0.027448  13.472  < 2e-16 ***
# s_state_d:landuse_factorHuman-modified  0.233030   0.041946   5.555 2.77e-08 ***
# s_state_d:landuse_factorDeciduous       0.227028   0.078026   2.910  0.00362 ** 
# s_state_d:landuse_factorMixed          -0.063947   0.032782  -1.951  0.05109 .  
# s_state_d:landuse_factorOpen/shrub/bog -0.038789   0.038097  -1.018  0.30861    
# s_state_d:landuse_factorNew forest      0.017968   0.028989   0.620  0.53537   


# ---------------------------------------------------------- time ------------------------------------------
TMBStruc3 <- glmmTMB(
  num_case_ ~ s_sl_ + s_ta_ + s_slope +
    s_minor_d + s_major_d + s_local_d + 
    landuse_factor +
    time_category:s_minor_d + time_category:s_major_d + time_category:s_local_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc3$parameters$theta[1] = log(1e3)  
TMBStruc3$mapArg = list(theta = factor(c(NA, 1)))
model_glmm3 <- glmmTMB:::fitTMB(TMBStruc3)
summary(model_glmm3)

#       AIC       BIC    logLik  deviance  df.resid 
#  405751.8  405947.3 -202856.9  405713.8    216956 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.507e-01    0.3882
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                                  Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                     -3.074444   7.123394  -0.432   0.6660    
# s_sl_                            0.135872   0.006667  20.381  < 2e-16 ***
# s_ta_                            0.006750   0.007516   0.898   0.3692    
# s_slope                         -0.011354   0.009688  -1.172   0.2412    
# s_minor_d                        0.190403   0.125377   1.519   0.1289    
# s_major_d                       -0.018827   0.132542  -0.142   0.8870    
# s_local_d                        0.171492   0.031093   5.515 3.48e-08 ***
# landuse_factorHuman-modified    -0.311774   0.046288  -6.735 1.63e-11 ***
# landuse_factorDeciduous          0.265840   0.053668   4.953 7.29e-07 ***
# landuse_factorMixed              0.066041   0.032766   2.016   0.0438 *  
# landuse_factorOpen/shrub/bog     0.060680   0.038845   1.562   0.1183    
# landuse_factorNew forest         0.373773   0.027325  13.679  < 2e-16 ***
# s_minor_d:time_categoryNight     0.256567   0.188957   1.358   0.1745    
# s_minor_d:time_categoryTwilight -0.165316   0.274620  -0.602   0.5472    
# s_major_d:time_categoryNight     0.321715   0.200112   1.608   0.1079    
# s_major_d:time_categoryTwilight  0.394182   0.285366   1.381   0.1672    
# s_local_d:time_categoryNight    -0.218753   0.047814  -4.575 4.76e-06 ***
# s_local_d:time_categoryTwilight -0.051250   0.067321  -0.761   0.4465 

# ---------------------------------------------------- time of day but 2 road classes ----------


TMBStruc3.0 <- glmmTMB(
  num_case_ ~ s_sl_ + s_ta_ + s_slope +
    s_state_d + s_local_d + 
    landuse_factor +
    time_category:s_state_d + time_category:s_local_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc3.0$parameters$theta[1] = log(1e3)  
TMBStruc3.0$mapArg = list(theta = factor(c(NA, 1)))
model_glmm3.0 <- glmmTMB:::fitTMB(TMBStruc3.0)
summary(model_glmm3.0)

saveRDS(model_glmm3.0, "model_glmm3.0.rds")


#       AIC       BIC    logLik  deviance  df.resid 
#  405734.5  405899.1 -202851.3  405702.5    216959 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance Std.Dev. 
#  str_ID (Intercept) 1.00e+06 1000.0000
#  id     (Intercept) 1.54e-01    0.3924
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                                  Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                     -3.081460   7.123458  -0.433   0.6653    
# s_sl_                            0.135851   0.006669  20.370  < 2e-16 ***
# s_ta_                            0.006971   0.007517   0.927   0.3538    
# s_slope                         -0.010868   0.009688  -1.122   0.2619    
# s_state_d                        0.256301   0.109390   2.343   0.0191 *  
# s_local_d                        0.160573   0.031034   5.174 2.29e-07 ***
# landuse_factorHuman-modified    -0.309913   0.046261  -6.699 2.09e-11 ***
# landuse_factorDeciduous          0.266943   0.053651   4.976 6.51e-07 ***
# landuse_factorMixed              0.069934   0.032772   2.134   0.0328 *  
# landuse_factorOpen/shrub/bog     0.063328   0.038821   1.631   0.1028    
# landuse_factorNew forest         0.377832   0.027336  13.822  < 2e-16 ***
# s_state_d:time_categoryNight     0.370654   0.166250   2.229   0.0258 *  
# s_state_d:time_categoryTwilight  0.104380   0.236822   0.441   0.6594    
# s_local_d:time_categoryNight    -0.225717   0.047971  -4.705 2.54e-06 ***
# s_local_d:time_categoryTwilight -0.039823   0.067126  -0.593   0.5530   

#remove ta_ predictor

TMBStruc3.0.1 <- glmmTMB(
  num_case_ ~  s_sl_ + s_slope +
    s_state_d + s_local_d + 
    landuse_factor +
    time_category:s_state_d + time_category:s_local_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc3.0.1$parameters$theta[1] = log(1e3)  
TMBStruc3.0.1$mapArg = list(theta = factor(c(NA, 1)))
model_glmm3.0.1 <- glmmTMB:::fitTMB(TMBStruc3.0.1)
summary(model_glmm3.0.1)

saveRDS(model_glmm3.0.1, "model_glmm3.0.1.rds")


#       AIC       BIC    logLik  deviance  df.resid 
#  405733.4  405887.7 -202851.7  405703.4    216960 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.524e-01    0.3904
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                                  Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                     -3.080069   7.123421  -0.432   0.6655    
# s_sl_                            0.135966   0.006668  20.390  < 2e-16 ***
# s_slope                         -0.010751   0.009685  -1.110   0.2670    
# s_state_d                        0.254844   0.109298   2.332   0.0197 *  
# s_local_d                        0.159868   0.031003   5.157 2.52e-07 ***
# landuse_factorHuman-modified    -0.308505   0.046220  -6.675 2.48e-11 ***
# landuse_factorDeciduous          0.267235   0.053637   4.982 6.28e-07 ***
# landuse_factorMixed              0.070115   0.032764   2.140   0.0324 *  
# landuse_factorOpen/shrub/bog     0.063681   0.038809   1.641   0.1008    
# landuse_factorNew forest         0.377999   0.027330  13.831  < 2e-16 ***
# s_state_d:time_categoryNight     0.370753   0.166126   2.232   0.0256 *  
# s_state_d:time_categoryTwilight  0.104618   0.236656   0.442   0.6584    
# s_local_d:time_categoryNight    -0.225806   0.047939  -4.710 2.47e-06 ***
# s_local_d:time_categoryTwilight -0.039562   0.067082  -0.590   0.5553    


# remove slope  predictor
TMBStruc3_3.0.2 <- glmmTMB(
  num_case_ ~ s_sl_ + 
    s_state_d + s_local_d + 
    landuse_factor +
    time_category:s_state_d + time_category:s_local_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc3_3.0.2$parameters$theta[1] = log(1e3)  
TMBStruc3_3.0.2$mapArg = list(theta = factor(c(NA, 1)))
model_glmm3_3.0.2 <- glmmTMB:::fitTMB(TMBStruc3_3.0.2)
summary(model_glmm3_3.0.2)

saveRDS(model_glmm3_3.0.2, "model_glmm3_3.0.2.rds")


#       AIC       BIC    logLik  deviance  df.resid 
#  405732.6  405876.7 -202852.3  405704.6    216961 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.492e-01    0.3863
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                                  Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                     -3.079240   7.123347  -0.432   0.6655    
# s_sl_                            0.135899   0.006668  20.382  < 2e-16 ***
# s_state_d                        0.256677   0.109279   2.349   0.0188 *  
# s_local_d                        0.161352   0.030972   5.210 1.89e-07 ***
# landuse_factorHuman-modified    -0.313413   0.046008  -6.812 9.62e-12 ***
# landuse_factorDeciduous          0.265081   0.053604   4.945 7.61e-07 ***
# landuse_factorMixed              0.068862   0.032744   2.103   0.0355 *  
# landuse_factorOpen/shrub/bog     0.062739   0.038800   1.617   0.1059    
# landuse_factorNew forest         0.376275   0.027286  13.790  < 2e-16 ***
# s_state_d:time_categoryNight     0.372085   0.166123   2.240   0.0251 *  
# s_state_d:time_categoryTwilight  0.103251   0.236655   0.436   0.6626    
# s_local_d:time_categoryNight    -0.225162   0.047934  -4.697 2.64e-06 ***
# s_local_d:time_categoryTwilight -0.039068   0.067071  -0.582   0.5602    

```


# -------------------------------- AIC based method --------------------------

```{r}
# Enhanced function that returns parameter estimates and metrics for summary table
run_stepwise_aic_selection <- function(data, model_type = "basic", max_steps = 7) {
  # Create results tracking data frame
  selection_history <- data.frame(
    Step = numeric(),
    Removed = character(),
    Formula = character(),
    AIC = numeric(),
    Delta_AIC = numeric(),
    stringsAsFactors = FALSE
  )
  
  # Function to fit a model with consistent settings
  fit_model <- function(formula_str) {
    model <- glmmTMB(
      as.formula(formula_str),
      family = poisson,
      data = data,
      doFit = FALSE
    )
    model$parameters$theta[1] = log(1e3)
    model$mapArg = list(theta = factor(c(NA, 1)))
    return(glmmTMB:::fitTMB(model))
  }
  
  # Choose initial formula and variables to test based on model type
  if (model_type == "basic") {
    current_formula <- "num_case_ ~ s_sl_ + s_ta_ + s_slope + s_state_d + s_local_d + landuse_factor + (1 | str_ID) + (1 | id)"
    variables_to_test <- c("s_ta_", "s_slope", "s_state_d", "s_local_d", "landuse_factor")
  } else if (model_type == "time") {
    current_formula <- "num_case_ ~ s_sl_ + s_ta_ + s_slope + s_state_d + s_local_d + landuse_factor + time_category:s_state_d + time_category:s_local_d + (1 | str_ID) + (1 | id)"
    variables_to_test <- c("s_ta_", "s_slope", "s_state_d", "s_local_d", "time_category:s_state_d", "time_category:s_local_d", "landuse_factor")
  } else if (model_type == "state_interaction") {
    current_formula <- "num_case_ ~ s_sl_ + s_ta_ + s_slope + s_state_d + landuse_factor + landuse_factor:s_state_d + (1 | str_ID) + (1 | id)"
    variables_to_test <- c("s_ta_", "s_slope", "landuse_factor", "s_state_d", "landuse_factor:s_state_d")
  } else if (model_type == "local_interaction") {
    current_formula <- "num_case_ ~ s_sl_ + s_ta_ + s_slope + s_local_d + landuse_factor + landuse_factor:s_local_d + (1 | str_ID) + (1 | id)"
    variables_to_test <- c("s_ta_", "s_slope", "landuse_factor", "s_local_d", "landuse_factor:s_local_d")
  } else if (model_type == "season") {
    current_formula <- "num_case_ ~ s_sl_ + s_ta_ + s_slope + s_state_d + s_local_d + landuse_factor + season:s_state_d + season:s_local_d + (1 | str_ID) + (1 | id)"
    variables_to_test <- c("s_ta_", "s_slope", "landuse_factor", "s_state_d", "s_local_d", "season:s_state_d", "season:s_local_d")
  } else {
    stop("Unknown model type")
  }
  
  # Initial model
  cat("Fitting initial model\n")
  current_model <- fit_model(current_formula)
  current_aic <- AIC(current_model)
  
  # Add to history
  selection_history <- rbind(selection_history, 
                            data.frame(
                              Step = 0,
                              Removed = "None",
                              Formula = current_formula,
                              AIC = current_aic,
                              Delta_AIC = 0,
                              stringsAsFactors = FALSE
                            ))
  
  # Store all models (including initial)
  all_models <- list()
  all_models[[1]] <- current_model
  
  # Iterate through steps
  for (step in 1:max_steps) {
    if (length(variables_to_test) == 0) {
      cat("No more variables to test. Stopping.\n")
      break
    }
    
    cat("\nStep", step, ": Testing removal of variables\n")
    cat("Current formula:", current_formula, "\n")
    cat("Variables to test:", paste(variables_to_test, collapse=", "), "\n\n")
    
    best_aic <- current_aic
    best_formula <- current_formula
    best_removed <- ""
    best_model <- NULL
    improved <- FALSE
    
    # Create a separate results table for this step
    step_results <- data.frame(
      Variable = character(),
      Formula = character(),
      AIC = numeric(),
      Delta_AIC = numeric(),
      stringsAsFactors = FALSE
    )
    
    # Test removing each variable
    for (var in variables_to_test) {
      # Create a new formula by directly replacing the variable
      # These patterns need to be customized for each variable
      if (var == "s_ta_") {
        new_formula <- gsub("\\+ s_ta_ \\+", "+ ", current_formula)
        new_formula <- gsub("s_ta_ \\+", "", new_formula)
      } else if (var == "s_slope") {
        new_formula <- gsub("\\+ s_slope \\+", "+ ", current_formula)
        new_formula <- gsub("s_slope \\+", "", new_formula)
      } else if (var == "s_state_d") {
        new_formula <- gsub("\\+ s_state_d \\+", "+ ", current_formula)
        new_formula <- gsub("s_state_d \\+", "", new_formula)
      } else if (var == "s_local_d") {
        new_formula <- gsub("\\+ s_local_d \\+", "+ ", current_formula)
        new_formula <- gsub("s_local_d \\+", "", new_formula)
      } else if (var == "landuse_factor") {
        new_formula <- gsub("\\+ landuse_factor \\+", "+ ", current_formula)
        new_formula <- gsub("landuse_factor \\+", "", new_formula)
      } else if (var == "time_category:s_state_d") {
        new_formula <- gsub("\\+ time_category:s_state_d \\+", "+ ", current_formula)
        new_formula <- gsub("time_category:s_state_d \\+", "", new_formula)
      } else if (var == "time_category:s_local_d") {
        new_formula <- gsub("\\+ time_category:s_local_d \\+", "+ ", current_formula)
        new_formula <- gsub("time_category:s_local_d \\+", "", new_formula)
      } else if (var == "landuse_factor:s_state_d") {
        new_formula <- gsub("\\+ landuse_factor:s_state_d \\+", "+ ", current_formula)
        new_formula <- gsub("landuse_factor:s_state_d \\+", "", new_formula)
      } else if (var == "landuse_factor:s_local_d") {
        new_formula <- gsub("\\+ landuse_factor:s_local_d \\+", "+ ", current_formula)
        new_formula <- gsub("landuse_factor:s_local_d \\+", "", new_formula)
      } else if (var == "season:s_state_d") {
        new_formula <- gsub("\\+ season:s_state_d \\+", "+ ", current_formula)
        new_formula <- gsub("season:s_state_d \\+", "", new_formula)
      } else if (var == "season:s_local_d") {
        new_formula <- gsub("\\+ season:s_local_d \\+", "+ ", current_formula)
        new_formula <- gsub("season:s_local_d \\+", "", new_formula)
      }      
      # Clean up any double spaces and trailing/leading +
      new_formula <- gsub("  ", " ", new_formula)
      new_formula <- gsub("\\+ \\)", "\\)", new_formula)
      
      cat("Testing without", var, "\n")
      cat("Formula:", new_formula, "\n")
      
      # Fit model and get AIC
      tryCatch({
        new_model <- fit_model(new_formula)
        new_aic <- AIC(new_model)
        
        # Add to step results
        step_results <- rbind(step_results, 
                              data.frame(
                                Variable = var,
                                Formula = new_formula,
                                AIC = new_aic,
                                Delta_AIC = new_aic - current_aic,
                                stringsAsFactors = FALSE
                              ))
        
        cat("AIC:", new_aic, "  Delta AIC:", new_aic - current_aic, "\n\n")
        
        # Check if this is the best so far
        if (new_aic < best_aic) {
          best_aic <- new_aic
          best_formula <- new_formula
          best_removed <- var
          best_model <- new_model
          improved <- TRUE
        }
      }, error = function(e) {
        cat("Error fitting model:", conditionMessage(e), "\n\n")
      })
    }
    
    # Print step results
    cat("=== Results for Step", step, "===\n")
    print(step_results[order(step_results$AIC), ])
    
    # If we found an improvement, update and continue
    if (improved) {
      cat("\nBest improvement at step", step, "by removing:", best_removed, "\n")
      cat("AIC improved from", current_aic, "to", best_aic, "(Δ:", best_aic - current_aic, ")\n")
      
      # Update current model
      current_formula <- best_formula
      current_model <- best_model
      current_aic <- best_aic
      
      # Store this model
      all_models[[step+1]] <- current_model
      
      # Remove variable from test list
      variables_to_test <- variables_to_test[variables_to_test != best_removed]
      
      # Add to history
      selection_history <- rbind(selection_history, 
                                data.frame(
                                  Step = step,
                                  Removed = best_removed,
                                  Formula = current_formula,
                                  AIC = current_aic,
                                  Delta_AIC = current_aic - selection_history$AIC[1],
                                  stringsAsFactors = FALSE
                                ))
    } else {
      cat("\nNo improvement found. Selection complete.\n")
      break
    }
  }
  
  # Final results
  cat("\n=== Final Model ===\n")
  cat("Formula:", current_formula, "\n")
  cat("AIC:", current_aic, "(Improvement from base:", current_aic - selection_history$AIC[1], ")\n\n")
  
  cat("=== Selection History ===\n")
  print(selection_history)
  
  # Extract summary data from the best model for table
  final_model_summary <- summary(current_model)
  
  # Extract fixed effects
  fixed_effects <- as.data.frame(final_model_summary$coefficients$cond)
  
  # Extract random effects variances
  rand_effects <- as.data.frame(VarCorr(current_model)$cond)
  rand_var_str_ID <- rand_effects[rand_effects$grp == "str_ID", "vcov"]
  rand_var_id <- rand_effects[rand_effects$grp == "id", "vcov"]
  
  # Calculate LogLik, DF, and other metrics
  loglik <- logLik(current_model)[1]
  df <- attr(logLik(current_model), "df")
  
  # Create table data
  model_data <- list(
    formula = current_formula,
    aic = current_aic,
    loglik = loglik,
    df = df,
    fixed_effects = fixed_effects,
    rand_var_str_ID = rand_var_str_ID,
    rand_var_id = rand_var_id,
    delta_aic = current_aic - selection_history$AIC[1],
    model_full = current_model
  )
  
  return(list(
    final_formula = current_formula,
    final_model = current_model,
    history = selection_history,
    all_models = all_models,
    model_data = model_data
  ))
}

# Function to extract data for summary table
extract_summary_table_data <- function(results_list) {
  # Initialize data frame to store all model results
  all_models_data <- data.frame()
  
  # Process each model type
  for (model_name in names(results_list)) {
    model_result <- results_list[[model_name]]
    model_data <- model_result$model_data
    
    # Get fixed effects estimates
    fixed_effects <- model_data$fixed_effects
    
    # Create row for this model
    model_row <- data.frame(
      model_name = model_name,
      AIC = model_data$aic,
      logLik = model_data$loglik,
      df = model_data$df,
      delta_AIC = model_data$delta_aic,
      weight = NA,  # Will calculate later
      stringsAsFactors = FALSE
    )
    
    # Add fixed effects columns (dynamically based on what's available)
    for (param in rownames(fixed_effects)) {
      col_name <- paste0(param, "_est")
      model_row[[col_name]] <- fixed_effects[param, "Estimate"]
      
      col_name_se <- paste0(param, "_se")
      model_row[[col_name_se]] <- fixed_effects[param, "Std. Error"]
    }
    
    # Add random effects
    model_row$rand_str_ID <- model_data$rand_var_str_ID
    model_row$rand_id <- model_data$rand_var_id
    
    # Add to complete data frame
    all_models_data <- rbind(all_models_data, model_row)
  }
  
  # Calculate AIC weights
  min_aic <- min(all_models_data$AIC)
  all_models_data$delta_AIC <- all_models_data$AIC - min_aic
  
  # Calculate exp(-0.5 * delta_AIC) for each model
  all_models_data$exp_value <- exp(-0.5 * all_models_data$delta_AIC)
  sum_exp <- sum(all_models_data$exp_value)
  
  # Calculate AIC weights
  all_models_data$weight <- all_models_data$exp_value / sum_exp
  
  # Sort by AIC
  all_models_data <- all_models_data[order(all_models_data$AIC), ]
  
  # Clean up - remove temporary column
  all_models_data$exp_value <- NULL
  
  return(all_models_data)
}
# 
# # Run all models once and store results
# all_model_results <- list()
# 
# # Run basic model
# cat("\n======= RUNNING BASIC MODEL =======\n")
# all_model_results[["basic"]] <- run_stepwise_aic_selection(steps3, model_type = "basic")
# 
# # Run time model
# cat("\n======= RUNNING TIME MODEL =======\n")
# all_model_results[["time"]] <- run_stepwise_aic_selection(steps3, model_type = "time")
# 
# # Run state interaction model
# cat("\n======= RUNNING STATE INTERACTION MODEL =======\n")
# all_model_results[["state_interaction"]] <- run_stepwise_aic_selection(steps3, model_type = "state_interaction")
# 
# # Run local interaction model
# cat("\n======= RUNNING LOCAL INTERACTION MODEL =======\n")
# all_model_results[["local_interaction"]] <- run_stepwise_aic_selection(steps3, model_type = "local_interaction")
# 
# Just run the season model and add it to your existing results
cat("\n======= RUNNING SEASON MODEL =======\n")
all_model_results_season[["season"]] <- run_stepwise_aic_selection(steps3, model_type = "season")
# 
# # Save the updated results
saveRDS(all_model_results_season, "saved_models/all_model_results_with_season.rds")


```



```{r table AICc}

all_model_results <- readRDS("saved_models/all_model_results.rds")
all_model_results_season <- readRDS("saved_models/all_model_results_with_season.rds")$season

# Function to recalculate AICs and weights for existing all_model_results
recalculate_model_metrics <- function(all_model_results) {
  # Create a list to hold updated tables for each model type
  updated_tables <- list()
  
  # Function to calculate AICc from AIC, df, and sample size
  calculate_aicc <- function(aic, df, n) {
    correction <- (2 * df * (df + 1)) / (n - df - 1)
    return(aic + correction)
  }
  
  # Process each model type
  for (model_name in names(all_model_results)) {
    cat("Processing model type:", model_name, "\n")
    model_obj <- all_model_results[[model_name]]
    
    # Get history of models for this type
    history <- model_obj$history
    if (is.null(history) || nrow(history) == 0) next
    
    # Get all models from this progression
    all_models <- model_obj$all_models
    
    # Create a results table with existing data
    model_steps <- data.frame(
      Step = history$Step,
      Removed = history$Removed,
      AIC = history$AIC,
      stringsAsFactors = FALSE
    )
    
    # Add columns for model parameters
    model_steps$Intercept <- NA
    model_steps$df <- NA
    model_steps$logLik <- NA
    model_steps$rand_str_ID <- NA
    model_steps$rand_id <- NA
    
    # Get sample size (n) from the first model
    n <- nobs(all_models[[1]])
    
    # Process each step
    for (i in 1:nrow(model_steps)) {
      if (i <= length(all_models) && !is.null(all_models[[i]])) {
        model <- all_models[[i]]
        
        # Extract fixed effects
        fixed_effects <- summary(model)$coefficients$cond
        
        # Add intercept
        int_idx <- which(rownames(fixed_effects) == "(Intercept)")
        if (length(int_idx) > 0) {
          model_steps$Intercept[i] <- fixed_effects[int_idx, "Estimate"]
        }
        
        # Add other parameters
        for (param in rownames(fixed_effects)) {
          if (param != "(Intercept)") {
            col_name <- paste0(param, "_est")
            if (!(col_name %in% names(model_steps))) {
              model_steps[[col_name]] <- NA
            }
            model_steps[[col_name]][i] <- fixed_effects[param, "Estimate"]
          }
        }
        
        # Extract random effects directly
        var_corr <- VarCorr(model)
        model_steps$rand_str_ID[i] <- var_corr$cond$str_ID[1,1]
        model_steps$rand_id[i] <- var_corr$cond$id[1,1]
        
        # Add df and logLik
        model_steps$df[i] <- attr(logLik(model), "df")
        model_steps$logLik[i] <- as.numeric(logLik(model))
      }
    }
    
    # Calculate AICc
    model_steps$AICc <- calculate_aicc(model_steps$AIC, model_steps$df, n)
    
    # Find minimum AICc (best model)
    min_aicc <- min(model_steps$AICc)
    
    # Calculate Delta AICc correctly (relative to best model)
    model_steps$delta <- model_steps$AICc - min_aicc
    
    # Calculate AICc weights correctly per Burnham & Anderson
    # This is the ONLY line that needed changing
    model_steps$weight <- exp(-0.5 * model_steps$delta) / sum(exp(-0.5 * model_steps$delta))
    
    # Sort the table by AICc (ascending order, best model first)
    model_steps <- model_steps[order(model_steps$AICc), ]
    
    # Store this table
    updated_tables[[model_name]] <- model_steps
  }
  
  return(updated_tables)
}

# Call the function on your existing results
updated_model_tables <- recalculate_model_metrics(all_model_results_season["season"])

write.csv(updated_model_tables, "updated_model_progression_new_season.csv", row.names = FALSE)

# Print and save updated tables
for (model_name in names(updated_model_tables)) {
  cat("\n=== Updated Model Progression for", model_name, "===\n")
  print(updated_model_tables[[model_name]])
  
  # Save to CSV
  file_name <- paste0("updated_model_progression_new_", model_name, ".csv")
  write.csv(updated_model_tables[[model_name]], file_name, row.names = FALSE)
}




```



# ---------------------------- OTHER MODELS -------------------------------------------------------


```{r other models}


#------------------------------------------------------------------season -------------------------------------



TMBStruc2.0 <- glmmTMB(
  num_case_ ~ s_sl_ + s_ta_ + s_slope +
    s_state_d + s_local_d + 
    landuse_factor +
    season:s_state_d + season:s_local_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc2.0$parameters$theta[1] = log(1e3)  
TMBStruc2.0$mapArg = list(theta = factor(c(NA, 1)))
model_glmm2.0 <- glmmTMB:::fitTMB(TMBStruc2.0)
summary(model_glmm2.0)


#       AIC       BIC    logLik  deviance  df.resid 
#  405736.8  405901.4 -202852.4  405704.8    216959 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.506e-01    0.3881
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                               Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                  -3.069432   7.123376  -0.431 0.666544    
# s_sl_                         0.135621   0.006675  20.318  < 2e-16 ***
# s_ta_                         0.007191   0.007517   0.957 0.338755    
# s_slope                      -0.010474   0.009685  -1.081 0.279480    
# s_state_d                     0.469615   0.126579   3.710 0.000207 ***
# s_local_d                    -0.052818   0.035977  -1.468 0.142076    
# landuse_factorHuman-modified -0.309841   0.046245  -6.700 2.08e-11 ***
# landuse_factorDeciduous       0.275035   0.053723   5.120 3.06e-07 ***
# landuse_factorMixed           0.071649   0.032774   2.186 0.028806 *  
# landuse_factorOpen/shrub/bog  0.068478   0.038857   1.762 0.078016 .  
# landuse_factorNew forest      0.378946   0.027345  13.858  < 2e-16 ***
# s_state_d:seasonSummer       -0.159593   0.175671  -0.908 0.363628    
# s_state_d:seasonSpring        0.012300   0.201704   0.061 0.951375    
# s_local_d:seasonSummer        0.235814   0.050229   4.695 2.67e-06 ***
# s_local_d:seasonSpring        0.152431   0.057880   2.634 0.008449 **  

# remove ta_ predictor

TMBStruc2.1 <- glmmTMB(
  num_case_ ~ s_sl_ + s_slope +
    s_state_d + s_local_d + 
    landuse_factor +
    season:s_state_d + season:s_local_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc2.1$parameters$theta[1] = log(1e3)  
TMBStruc2.1$mapArg = list(theta = factor(c(NA, 1)))
model_glmm2.1 <- glmmTMB:::fitTMB(TMBStruc2.1)
summary(model_glmm2.1)

#       AIC       BIC    logLik  deviance  df.resid 
#  405735.7  405890.0 -202852.8  405705.7    216960 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance Std.Dev. 
#  str_ID (Intercept) 1.00e+06 1000.0000
#  id     (Intercept) 1.51e-01    0.3886
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                               Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                  -3.073768   7.123373  -0.432 0.666102    
# s_sl_                         0.135740   0.006674  20.339  < 2e-16 ***
# s_slope                      -0.010360   0.009681  -1.070 0.284577    
# s_state_d                     0.468612   0.126473   3.705 0.000211 ***
# s_local_d                    -0.053452   0.035945  -1.487 0.136998    
# landuse_factorHuman-modified -0.308415   0.046203  -6.675 2.47e-11 ***
# landuse_factorDeciduous       0.275359   0.053709   5.127 2.95e-07 ***
# landuse_factorMixed           0.071790   0.032765   2.191 0.028449 *  
# landuse_factorOpen/shrub/bog  0.068868   0.038844   1.773 0.076237 .  
# landuse_factorNew forest      0.379114   0.027339  13.867  < 2e-16 ***
# s_state_d:seasonSummer       -0.159772   0.175534  -0.910 0.362713    
# s_state_d:seasonSpring        0.011062   0.201547   0.055 0.956231    
# s_local_d:seasonSummer        0.235661   0.050194   4.695 2.67e-06 ***
# s_local_d:seasonSpring        0.152405   0.057839   2.635 0.008414 ** 

# remove slope predictor
TMBStruc2.2 <- glmmTMB(
  num_case_ ~ s_sl_ +
    s_state_d + s_local_d + 
    landuse_factor +
    season:s_state_d + season:s_local_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc2.2$parameters$theta[1] = log(1e3)  
TMBStruc2.2$mapArg = list(theta = factor(c(NA, 1)))
model_glmm2.2 <- glmmTMB:::fitTMB(TMBStruc2.2)
summary(model_glmm2.2)

#       AIC       BIC    logLik  deviance  df.resid 
#  405734.9  405878.9 -202853.4  405706.9    216961 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.501e-01    0.3874
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                               Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                  -3.069602   7.123372  -0.431 0.666527    
# s_sl_                         0.135681   0.006673  20.332  < 2e-16 ***
# s_state_d                     0.471642   0.126444   3.730 0.000191 ***
# s_local_d                    -0.051963   0.035915  -1.447 0.147944    
# landuse_factorHuman-modified -0.313174   0.045987  -6.810 9.76e-12 ***
# landuse_factorDeciduous       0.273342   0.053676   5.092 3.54e-07 ***
# landuse_factorMixed           0.070616   0.032746   2.156 0.031045 *  
# landuse_factorOpen/shrub/bog  0.068008   0.038835   1.751 0.079909 .  
# landuse_factorNew forest      0.377448   0.027295  13.828  < 2e-16 ***
# s_state_d:seasonSummer       -0.160395   0.175518  -0.914 0.360804    
# s_state_d:seasonSpring        0.008238   0.201563   0.041 0.967397    
# s_local_d:seasonSummer        0.235669   0.050187   4.696 2.65e-06 ***
# s_local_d:seasonSpring        0.153335   0.057838   2.651 0.008022 ** 

# remove state interaction predictor
TMBStruc2.3 <- glmmTMB(
  num_case_ ~ s_sl_ +
    s_state_d + s_local_d + 
    landuse_factor +
    season:s_local_d +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc2.3$parameters$theta[1] = log(1e3)  
TMBStruc2.3$mapArg = list(theta = factor(c(NA, 1)))
model_glmm2.3 <- glmmTMB:::fitTMB(TMBStruc2.3)
summary(model_glmm2.3)


#       AIC       BIC    logLik  deviance  df.resid 
#  405731.9  405855.4 -202854.0  405707.9    216963 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.491e-01    0.3862
# Number of obs: 216975, groups:  str_ID, 19725; id, 8
# 
# Conditional model:
#                               Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                  -3.069358   7.123343  -0.431   0.6666    
# s_sl_                         0.135677   0.006671  20.337  < 2e-16 ***
# s_state_d                     0.410250   0.076768   5.344 9.09e-08 ***
# s_local_d                    -0.049187   0.035608  -1.381   0.1672    
# landuse_factorHuman-modified -0.314120   0.045978  -6.832 8.37e-12 ***
# landuse_factorDeciduous       0.273108   0.053675   5.088 3.62e-07 ***
# landuse_factorMixed           0.070487   0.032744   2.153   0.0313 *  
# landuse_factorOpen/shrub/bog  0.067905   0.038836   1.749   0.0804 .  
# landuse_factorNew forest      0.377491   0.027296  13.830  < 2e-16 ***
# s_local_d:seasonSummer        0.229840   0.049725   4.622 3.80e-06 ***
# s_local_d:seasonSpring        0.153335   0.057153   2.683   0.0073 ** 




#------------------------------------------------- making road crossing detection -----------------------

steps3$row_id <- 1:nrow(steps3)

steps_lines <- st_sf(
  geometry = mapply(
    function(x1, y1, x2, y2) {
      st_linestring(matrix(c(x1, y1, x2, y2), ncol = 2, byrow = TRUE))
    },
    steps3$x1_, steps3$y1_, steps3$x2_, steps3$y2_,
    SIMPLIFY = FALSE
  ),
  row_id = steps3$row_id,
  step_id_ = steps3$step_id_,
  case_ = steps3$case_,
  crs = 3301
) 


# data frame with crossing information
crossing_data <- data.frame(
  row_id = steps_lines$row_id,
  crosses_major = lengths(st_intersects(steps_lines, roads[roads$class >= 2, ])) > 0,
  crosses_minor = lengths(st_intersects(steps_lines, roads[roads$class == 1, ])) > 0,
  crosses_local = lengths(st_intersects(steps_lines, roads[roads$class == 0, ])) > 0
)

#crossing information back to steps3
steps3 <- merge(steps3, crossing_data, by = "row_id", all.x = TRUE)
steps3$crosses_state <- steps3$crosses_major | steps3$crosses_minor



table(steps3$crosses_major[steps3$case_ == 'FALSE'])
#  FALSE   TRUE 
# 196254    506 
table(steps3$crosses_minor[steps3$case_ == 'FALSE'])
#  FALSE   TRUE 
# 196533    227 
table(steps3$crosses_local[steps3$case_ == 'FALSE'])
#  FALSE   TRUE 
# 187404   9356 
table(steps3$crosses_major[steps3$case_ == 'TRUE'])
# FALSE  TRUE 
# 19657    19 
table(steps3$crosses_minor[steps3$case_ == 'TRUE'])
# FALSE  TRUE 
# 19645    31 
table(steps3$crosses_local[steps3$case_ == 'TRUE'])
# FALSE  TRUE 
# 18920   756 

# -------------------------------------------------------------------- crossing  -------------

# Define GLMM structure without fitting
TMBStruc22 <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_minor + crosses_major + crosses_local + 
    landuse_factor +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc22$parameters$theta[1] = log(1e3)  

TMBStruc22$mapArg = list(theta = factor(c(NA, 1)))

model_glmm22 <- glmmTMB:::fitTMB(TMBStruc22)

summary(model_glmm22)

#       AIC       BIC    logLik  deviance  df.resid 
#  364523.2  364635.2 -182250.6  364501.2    194810 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.528e-01    0.3909
# Number of obs: 194821, groups:  str_ID, 17711; id, 8
# 
# Conditional model:
#                               Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                  -2.889117   7.517020  -0.384   0.7007    
# log_sl_                       0.152736   0.008532  17.902  < 2e-16 ***
# cos_ta_                       0.009919   0.007932   1.251   0.2111    
# crosses_minorTRUE             0.430581   0.217417   1.980   0.0477 *  
# crosses_majorTRUE            -1.064889   0.244930  -4.348 1.38e-05 ***
# crosses_localTRUE            -0.396981   0.045602  -8.705  < 2e-16 ***
# landuse_factorHuman-modified -0.497643   0.048607 -10.238  < 2e-16 ***
# landuse_factorDeciduous       0.235597   0.058366   4.037 5.42e-05 ***
# landuse_factorMixed          -0.029234   0.036510  -0.801   0.4233    
# landuse_factorOpen/shrub/bog -0.039269   0.040255  -0.976   0.3293  


# Define GLMM structure without fitting
TMBStruc22.1 <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_state+ crosses_local + 
    landuse_factor +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc22.1$parameters$theta[1] = log(1e3)  

TMBStruc22.1$mapArg = list(theta = factor(c(NA, 1)))

model_glmm22.1 <- glmmTMB:::fitTMB(TMBStruc22.1)

summary(model_glmm22.1)

#       AIC       BIC    logLik  deviance  df.resid 
#  404794.5  404907.6 -202386.3  404772.5    216425 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.505e-01    0.3879
# Number of obs: 216436, groups:  str_ID, 19676; id, 8
# 
# Conditional model:
#                               Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                  -3.034393   7.132197  -0.425  0.67051    
# log_sl_                       0.146088   0.008085  18.069  < 2e-16 ***
# cos_ta_                       0.007087   0.007518   0.943  0.34586    
# crosses_stateTRUE            -0.505611   0.157549  -3.209  0.00133 ** 
# crosses_localTRUE            -0.388381   0.044507  -8.726  < 2e-16 ***
# landuse_factorHuman-modified -0.321049   0.045711  -7.023 2.16e-12 ***
# landuse_factorDeciduous       0.242579   0.053416   4.541 5.59e-06 ***
# landuse_factorMixed           0.033149   0.032871   1.008  0.31324    
# landuse_factorOpen/shrub/bog  0.046538   0.039024   1.193  0.23305    
# landuse_factorNew forest      0.360495   0.027393  13.160  < 2e-16 ***

# ---- crossing with landuse interaction -----

# Model for major roads only 
TMBStruc_major <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_major + landuse_factor + landuse_factor:crosses_major +
    (1 | str_ID) + (1 | id), 
  family = poisson, data = steps3, doFit = FALSE
)
TMBStruc_major$parameters$theta[1] = log(1e3)  
TMBStruc_major$mapArg = list(theta = factor(c(NA, 1)))
model_glmm_major <- glmmTMB:::fitTMB(TMBStruc_major)
summary(model_glmm_major)

#       AIC       BIC    logLik  deviance  df.resid 
#  404836.1  404990.4 -202403.1  404806.1    216421 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance Std.Dev. 
#  str_ID (Intercept) 1.00e+06 1000.0000
#  id     (Intercept) 1.55e-01    0.3937
# Number of obs: 216436, groups:  str_ID, 19676; id, 8
# 
# Conditional model:
#                                                  Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                     -3.121350   7.132286  -0.438  0.66165    
# log_sl_                                          0.133779   0.007911  16.911  < 2e-16 ***
# cos_ta_                                         -0.002659   0.007498  -0.355  0.72287    
# crosses_majorTRUE                               -1.210769   0.396425  -3.054  0.00226 ** 
# landuse_factorHuman-modified                    -0.374800   0.045678  -8.205 2.30e-16 ***
# landuse_factorDeciduous                          0.275554   0.053571   5.144 2.69e-07 ***
# landuse_factorMixed                              0.035282   0.032877   1.073  0.28321    
# landuse_factorOpen/shrub/bog                     0.021940   0.038952   0.563  0.57326    
# landuse_factorNew forest                         0.352404   0.027324  12.897  < 2e-16 ***
# crosses_majorTRUE:landuse_factorHuman-modified  -0.577308   0.818516  -0.705  0.48062    
# crosses_majorTRUE:landuse_factorDeciduous       -5.754605  35.374804  -0.163  0.87077    
# crosses_majorTRUE:landuse_factorMixed          -11.072074 176.679731  -0.063  0.95003    
# crosses_majorTRUE:landuse_factorOpen/shrub/bog   0.820626   0.851219   0.964  0.33502    
# crosses_majorTRUE:landuse_factorNew forest       0.840924   0.537496   1.565  0.11770   

# Model for minor roads only
TMBStruc_minor <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_minor + landuse_factor + landuse_factor:crosses_minor +
    (1 | str_ID) + (1 | id), 
  family = poisson, data = steps3, doFit = FALSE
)
TMBStruc_minor$parameters$theta[1] = log(1e3)  
TMBStruc_minor$mapArg = list(theta = factor(c(NA, 1)))
model_glmm_minor <- glmmTMB:::fitTMB(TMBStruc_minor)
summary(model_glmm_minor)

#       AIC       BIC    logLik  deviance  df.resid 
#  404887.3  405041.5 -202428.6  404857.3    216421 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.584e-01    0.3979
# Number of obs: 216436, groups:  str_ID, 19676; id, 8
# 
# Conditional model:
#                                                  Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                     -3.134067   7.132365  -0.439    0.660    
# log_sl_                                          0.129696   0.007893  16.431  < 2e-16 ***
# cos_ta_                                          0.003916   0.007508   0.522    0.602    
# crosses_minorTRUE                                0.827793   0.792521   1.045    0.296    
# landuse_factorHuman-modified                    -0.346678   0.045641  -7.596 3.06e-14 ***
# landuse_factorDeciduous                          0.238571   0.053403   4.467 7.92e-06 ***
# landuse_factorMixed                              0.030468   0.032836   0.928    0.353    
# landuse_factorOpen/shrub/bog                     0.045672   0.038953   1.172    0.241    
# landuse_factorNew forest                         0.362230   0.027372  13.234  < 2e-16 ***
# crosses_minorTRUE:landuse_factorHuman-modified  -0.376107   0.840768  -0.447    0.655    
# crosses_minorTRUE:landuse_factorDeciduous       -6.670864  36.615272  -0.182    0.855    
# crosses_minorTRUE:landuse_factorMixed           -0.531118   0.910766  -0.583    0.560    
# crosses_minorTRUE:landuse_factorOpen/shrub/bog -11.515398 137.840339  -0.084    0.933    
# crosses_minorTRUE:landuse_factorNew forest      -0.397274   0.886014  -0.448    0.654 



# Model for local roads only
TMBStruc_local <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_local + landuse_factor + landuse_factor:crosses_local +
    (1 | str_ID) + (1 | id), 
  family = poisson, data = steps3, doFit = FALSE
)
TMBStruc_local$parameters$theta[1] = log(1e3)  
TMBStruc_local$mapArg = list(theta = factor(c(NA, 1)))
model_glmm_local <- glmmTMB:::fitTMB(TMBStruc_local)
summary(model_glmm_local)


#       AIC       BIC    logLik  deviance  df.resid 
#  404791.3  404945.6 -202380.7  404761.3    216421 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.526e-01    0.3907
# Number of obs: 216436, groups:  str_ID, 19676; id, 8
# 
# Conditional model:
#                                                 Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                    -3.033812   7.132235  -0.425  0.67057    
# log_sl_                                         0.143855   0.008063  17.840  < 2e-16 ***
# cos_ta_                                         0.006728   0.007518   0.895  0.37082    
# crosses_localTRUE                              -0.487034   0.106486  -4.574 4.79e-06 ***
# landuse_factorHuman-modified                   -0.311997   0.046971  -6.642 3.09e-11 ***
# landuse_factorDeciduous                         0.243007   0.053949   4.504 6.66e-06 ***
# landuse_factorMixed                             0.036068   0.033472   1.078  0.28122    
# landuse_factorOpen/shrub/bog                    0.045872   0.039909   1.149  0.25039    
# landuse_factorNew forest                        0.344017   0.027925  12.319  < 2e-16 ***
# crosses_localTRUE:landuse_factorHuman-modified -0.043880   0.140148  -0.313  0.75421    
# crosses_localTRUE:landuse_factorDeciduous      -0.064051   0.267828  -0.239  0.81099    
# crosses_localTRUE:landuse_factorMixed          -0.048188   0.141362  -0.341  0.73319    
# crosses_localTRUE:landuse_factorOpen/shrub/bog  0.057982   0.162816   0.356  0.72175    
# crosses_localTRUE:landuse_factorNew forest      0.397495   0.126559   3.141  0.00168 ** 

# Model for state roads only (major + minor)
TMBStruc_state <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_state + landuse_factor + landuse_factor:crosses_state +
    (1 | str_ID) + (1 | id), 
  family = poisson, data = steps3, doFit = FALSE
)
TMBStruc_state$parameters$theta[1] = log(1e3)  
TMBStruc_state$mapArg = list(theta = factor(c(NA, 1)))
model_glmm_state <- glmmTMB:::fitTMB(TMBStruc_state)
summary(model_glmm_state)

#       AIC       BIC    logLik  deviance  df.resid 
#  404875.7  405029.9 -202422.8  404845.7    216421 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.622e-01    0.4027
# Number of obs: 216436, groups:  str_ID, 19676; id, 8
# 
# Conditional model:
#                                                  Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                     -3.060150   7.132441  -0.429  0.66789    
# log_sl_                                          0.132360   0.007911  16.731  < 2e-16 ***
# cos_ta_                                          0.004402   0.007509   0.586  0.55773    
# crosses_stateTRUE                               -0.941005   0.351594  -2.676  0.00744 ** 
# landuse_factorHuman-modified                    -0.344694   0.045702  -7.542 4.62e-14 ***
# landuse_factorDeciduous                          0.239500   0.053468   4.479 7.49e-06 ***
# landuse_factorMixed                              0.029806   0.032848   0.907  0.36420    
# landuse_factorOpen/shrub/bog                     0.041836   0.038966   1.074  0.28298    
# landuse_factorNew forest                         0.358799   0.027405  13.092  < 2e-16 ***
# crosses_stateTRUE:landuse_factorHuman-modified   0.596169   0.442612   1.347  0.17800    
# crosses_stateTRUE:landuse_factorDeciduous       -9.651756 131.037503  -0.074  0.94128    
# crosses_stateTRUE:landuse_factorMixed            0.153345   0.552349   0.278  0.78130    
# crosses_stateTRUE:landuse_factorOpen/shrub/bog   0.057800   0.809374   0.071  0.94307    
# crosses_stateTRUE:landuse_factorNew forest       0.834671   0.439109   1.901  0.05732 . 

#------------------------------------------------------------------season 2: with crossing --------------------------
# Define GLMM structure without fitting
TMBStruc33 <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_minor + crosses_major + crosses_local + 
    landuse_factor +
    factor(season):crosses_minor + factor(season):crosses_major + factor(season):crosses_local +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc33$parameters$theta[1] = log(1e3)  

TMBStruc33$mapArg = list(theta = factor(c(NA, 1)))

model_glmm33 <- glmmTMB:::fitTMB(TMBStruc33)

summary(model_glmm33)

#       AIC       BIC    logLik  deviance  df.resid 
#  364519.3  364712.7 -182240.6  364481.3    194802 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.852e-01    0.4303
# Number of obs: 194821, groups:  str_ID, 17711; id, 8
# 
# Conditional model:
#                                          Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                             -2.805462  12.928231  -0.217 0.828206    
# log_sl_                                  0.152628   0.008531  17.890  < 2e-16 ***
# cos_ta_                                  0.010191   0.007933   1.285 0.198949    
# crosses_minorTRUE                        0.552465   0.319454   1.729 0.083737 .  
# crosses_majorTRUE                       -0.595107   0.358432  -1.660 0.096853 .  
# crosses_localTRUE                       -0.276450   0.077844  -3.551 0.000383 ***
# landuse_factorHuman-modified            -0.499699   0.048623 -10.277  < 2e-16 ***
# landuse_factorDeciduous                  0.233602   0.058356   4.003 6.25e-05 ***
# landuse_factorMixed                     -0.030514   0.036512  -0.836 0.403316    
# landuse_factorOpen/shrub/bog            -0.041978   0.040286  -1.042 0.297416    
# crosses_minorFALSE:factor(season)Summer  0.115324  17.845459   0.006 0.994844    
# crosses_minorTRUE:factor(season)Summer  -1.353534  17.863601  -0.076 0.939602    
# crosses_minorFALSE:factor(season)Winter -0.474857  19.036783  -0.025 0.980099    
# crosses_minorTRUE:factor(season)Winter  -0.203714  19.042630  -0.011 0.991465    
# crosses_majorTRUE:factor(season)Summer  -0.176694   0.543362  -0.325 0.745040    
# crosses_majorTRUE:factor(season)Winter  -1.533119   0.697401  -2.198 0.027925 *  
# crosses_localTRUE:factor(season)Summer  -0.090096   0.105826  -0.851 0.394569    
# crosses_localTRUE:factor(season)Winter  -0.298422   0.114455  -2.607 0.009125 ** 

TMBStruc33.1 <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_state + crosses_local + 
    landuse_factor +
    factor(season):crosses_state + factor(season):crosses_local +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc33.1$parameters$theta[1] = log(1e3)  

TMBStruc33.1$mapArg = list(theta = factor(c(NA, 1)))

model_glmm33.1 <- glmmTMB:::fitTMB(TMBStruc33.1)

summary(model_glmm33.1)

#       AIC       BIC    logLik  deviance  df.resid 
#  404801.3  404976.1 -202383.6  404767.3    216419 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.782e-01    0.4221
# Number of obs: 216436, groups:  str_ID, 19676; id, 8
# 
# Conditional model:
#                                          Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                             -2.798896  11.607314  -0.241   0.8095    
# log_sl_                                  0.145951   0.008085  18.052  < 2e-16 ***
# cos_ta_                                  0.007143   0.007518   0.950   0.3421    
# crosses_stateTRUE                       -0.461608   0.231307  -1.996   0.0460 *  
# crosses_localTRUE                       -0.481880   0.072439  -6.652 2.89e-11 ***
# landuse_factorHuman-modified            -0.320839   0.045728  -7.016 2.28e-12 ***
# landuse_factorDeciduous                  0.242201   0.053398   4.536 5.74e-06 ***
# landuse_factorMixed                      0.033526   0.032870   1.020   0.3078    
# landuse_factorOpen/shrub/bog             0.046380   0.039025   1.188   0.2347    
# landuse_factorNew forest                 0.360306   0.027393  13.153  < 2e-16 ***
# crosses_stateFALSE:factor(season)Summer -0.333922  16.439546  -0.020   0.9838    
# crosses_stateTRUE:factor(season)Summer  -0.773003  16.444946  -0.047   0.9625    
# crosses_stateFALSE:factor(season)Spring -0.418961  18.434138  -0.023   0.9819    
# crosses_stateTRUE:factor(season)Spring  -0.235523  18.437575  -0.013   0.9898    
# crosses_localTRUE:factor(season)Summer   0.125895   0.101196   1.244   0.2135    
# crosses_localTRUE:factor(season)Spring   0.188938   0.112711   1.676   0.0937 . 


TMBStruc33.2 <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_state + crosses_local + 
    landuse_factor +
    factor(season):crosses_local +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc33.2$parameters$theta[1] = log(1e3)  

TMBStruc33.2$mapArg = list(theta = factor(c(NA, 1)))

model_glmm33.2 <- glmmTMB:::fitTMB(TMBStruc33.2)

summary(model_glmm33.2)

#       AIC       BIC    logLik  deviance  df.resid 
#  404799.4  404953.6 -202384.7  404769.4    216421 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.793e-01    0.4234
# Number of obs: 216436, groups:  str_ID, 19676; id, 8
# 
# Conditional model:
#                                          Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                             -2.706548  11.607278  -0.233  0.81562    
# log_sl_                                  0.145976   0.008085  18.055  < 2e-16 ***
# cos_ta_                                  0.007176   0.007518   0.954  0.33985    
# crosses_stateTRUE                       -0.507398   0.157490  -3.222  0.00127 ** 
# crosses_localTRUE                       -0.481597   0.072430  -6.649 2.95e-11 ***
# landuse_factorHuman-modified            -0.320364   0.045720  -7.007 2.43e-12 ***
# landuse_factorDeciduous                  0.242304   0.053407   4.537 5.71e-06 ***
# landuse_factorMixed                      0.033548   0.032869   1.021  0.30742    
# landuse_factorOpen/shrub/bog             0.046240   0.039024   1.185  0.23605    
# landuse_factorNew forest                 0.360364   0.027391  13.156  < 2e-16 ***
# crosses_localFALSE:factor(season)Summer -0.563057  16.439494  -0.034  0.97268    
# crosses_localTRUE:factor(season)Summer  -0.440928  16.439781  -0.027  0.97860    
# crosses_localFALSE:factor(season)Spring -0.425244  18.434145  -0.023  0.98160    
# crosses_localTRUE:factor(season)Spring  -0.233712  18.434462  -0.013  0.98988    

# ---------------------------------------------------------- time 2: with crossings -----------------------
TMBStruc44 <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_minor + crosses_major + crosses_local + 
    landuse_factor +
    factor(time_category):crosses_minor + factor(time_category):crosses_major + factor(time_category):crosses_local +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc44$parameters$theta[1] = log(1e3)  

TMBStruc44$mapArg = list(theta = factor(c(NA, 1)))

model_glmm44 <- glmmTMB:::fitTMB(TMBStruc44)

summary(model_glmm44)

#       AIC       BIC    logLik  deviance  df.resid 
#  364525.7  364719.1 -182243.9  364487.7    194802 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance Std.Dev.
#  str_ID (Intercept) 1.00e+06 1000.000
#  id     (Intercept) 1.73e-01    0.416
# 
# Conditional model:
#                                                   Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                      -2.493584  10.776294  -0.231   0.8170    
# log_sl_                                           0.152652   0.008533  17.890  < 2e-16 ***
# cos_ta_                                           0.009900   0.007932   1.248   0.2120    
# crosses_minorTRUE                                -0.052670   0.419994  -0.125   0.9002    
# crosses_majorTRUE                                -1.841373   0.589824  -3.122   0.0018 ** 
# crosses_localTRUE                                -0.408808   0.074578  -5.482 4.22e-08 ***
# landuse_factorHuman-modified                     -0.498646   0.048632 -10.254  < 2e-16 ***
# landuse_factorDeciduous                           0.234875   0.058379   4.023 5.74e-05 ***
# landuse_factorMixed                              -0.029332   0.036517  -0.803   0.4218    
# landuse_factorOpen/shrub/bog                     -0.038921   0.040264  -0.967   0.3337    
# crosses_minorFALSE:factor(time_category)Night    -0.739037  16.215502  -0.046   0.9636    
# crosses_minorTRUE:factor(time_category)Night     -0.132759  16.223472  -0.008   0.9935    
# crosses_minorFALSE:factor(time_category)Twilight -0.732099  23.523036  -0.031   0.9752    
# crosses_minorTRUE:factor(time_category)Twilight   0.465979  23.535007   0.020   0.9842    
# crosses_majorTRUE:factor(time_category)Night      0.923753   0.668422   1.382   0.1670    
# crosses_majorTRUE:factor(time_category)Twilight   1.474727   0.814244   1.811   0.0701 .  
# crosses_localTRUE:factor(time_category)Night     -0.050600   0.097499  -0.519   0.6038    
# crosses_localTRUE:factor(time_category)Twilight   0.296533   0.141770   2.092   0.0365 *  



TMBStruc44.1 <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_minor + crosses_major + crosses_local + 
    landuse_factor +
    factor(time_category):crosses_major + factor(time_category):crosses_local +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc44.1$parameters$theta[1] = log(1e3)  

TMBStruc44.1$mapArg = list(theta = factor(c(NA, 1)))

model_glmm44.1 <- glmmTMB:::fitTMB(TMBStruc44.1)

summary(model_glmm44.1)


#       AIC       BIC    logLik  deviance  df.resid 
#  404797.2  404982.3 -202380.6  404761.2    216418 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.768e-01    0.4205
# Number of obs: 216436, groups:  str_ID, 19676; id, 8
# 
# Conditional model:
#                                                   Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                      -2.581427  10.143135  -0.254  0.79911    
# log_sl_                                           0.145857   0.008074  18.064  < 2e-16 ***
# cos_ta_                                           0.006827   0.007516   0.908  0.36377    
# crosses_minorTRUE                                 0.454830   0.213478   2.131  0.03312 *  
# crosses_majorTRUE                                -1.811236   0.589111  -3.075  0.00211 ** 
# crosses_localTRUE                                -0.366286   0.073226  -5.002 5.67e-07 ***
# landuse_factorHuman-modified                     -0.323569   0.045819  -7.062 1.64e-12 ***
# landuse_factorDeciduous                           0.280108   0.053764   5.210 1.89e-07 ***
# landuse_factorMixed                               0.055612   0.032873   1.692  0.09070 .  
# landuse_factorOpen/shrub/bog                      0.051683   0.039172   1.319  0.18705    
# landuse_factorNew forest                          0.357185   0.027352  13.059  < 2e-16 ***
# crosses_majorFALSE:factor(time_category)Night    -0.860312  15.372811  -0.056  0.95537    
# crosses_majorTRUE:factor(time_category)Night     -0.017470  15.387240  -0.001  0.99909    
# crosses_majorFALSE:factor(time_category)Twilight -0.885312  22.568467  -0.039  0.96871    
# crosses_majorTRUE:factor(time_category)Twilight   0.629273  22.582900   0.028  0.97777    
# crosses_localTRUE:factor(time_category)Night     -0.046948   0.095248  -0.493  0.62208    
# crosses_localTRUE:factor(time_category)Twilight   0.348967   0.139523   2.501  0.01238 *  



TMBStruc44.2 <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_minor + crosses_major + crosses_local + 
    landuse_factor +
    factor(time_category):crosses_local +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc44.2$parameters$theta[1] = log(1e3)  

TMBStruc44.2$mapArg = list(theta = factor(c(NA, 1)))

model_glmm44.2 <- glmmTMB:::fitTMB(TMBStruc44.2)

summary(model_glmm44.2)


#       AIC       BIC    logLik  deviance  df.resid 
#  404796.9  404961.5 -202382.5  404764.9    216420 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev.
#  str_ID (Intercept) 1.000e+06 1000.000
#  id     (Intercept) 1.772e-01    0.421
# Number of obs: 216436, groups:  str_ID, 19676; id, 8
# 
# Conditional model:
#                                                   Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                      -2.794748  10.143083  -0.276   0.7829    
# log_sl_                                           0.145873   0.008074  18.066  < 2e-16 ***
# cos_ta_                                           0.006888   0.007516   0.916   0.3594    
# crosses_minorTRUE                                 0.456420   0.213455   2.138   0.0325 *  
# crosses_majorTRUE                                -1.075378   0.243580  -4.415 1.01e-05 ***
# crosses_localTRUE                                -0.370653   0.073157  -5.067 4.05e-07 ***
# landuse_factorHuman-modified                     -0.323886   0.045812  -7.070 1.55e-12 ***
# landuse_factorDeciduous                           0.280445   0.053763   5.216 1.82e-07 ***
# landuse_factorMixed                               0.055532   0.032873   1.689   0.0912 .  
# landuse_factorOpen/shrub/bog                      0.051238   0.039171   1.308   0.1909    
# landuse_factorNew forest                          0.357247   0.027353  13.061  < 2e-16 ***
# crosses_localFALSE:factor(time_category)Night    -0.502129  15.372757  -0.033   0.9739    
# crosses_localTRUE:factor(time_category)Night     -0.544434  15.373030  -0.035   0.9717    
# crosses_localFALSE:factor(time_category)Twilight -0.344569  22.568425  -0.015   0.9878    
# crosses_localTRUE:factor(time_category)Twilight   0.013748  22.568822   0.001   0.9995 

# -------------------------------------------------------------- crosses time with 2 road -------------------------

TMBStruc55 <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_state+ crosses_local + 
    landuse_factor +
    factor(time_category):crosses_state + factor(time_category):crosses_local +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc55$parameters$theta[1] = log(1e3)  

TMBStruc55$mapArg = list(theta = factor(c(NA, 1)))

model_glmm55 <- glmmTMB:::fitTMB(TMBStruc55)

summary(model_glmm55)


#       AIC       BIC    logLik  deviance  df.resid 
#  404814.5  404989.3 -202390.2  404780.5    216419 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance Std.Dev. 
#  str_ID (Intercept) 1.00e+06 1000.0000
#  id     (Intercept) 1.74e-01    0.4171
# Number of obs: 216436, groups:  str_ID, 19676; id, 8
# 
# Conditional model:
#                                                   Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                      -2.617208  10.143089  -0.258  0.79638    
# log_sl_                                           0.146005   0.008075  18.082  < 2e-16 ***
# cos_ta_                                           0.006794   0.007516   0.904  0.36600    
# crosses_stateTRUE                                -0.983236   0.331830  -2.963  0.00305 ** 
# crosses_localTRUE                                -0.367865   0.073207  -5.025 5.04e-07 ***
# landuse_factorHuman-modified                     -0.319961   0.045802  -6.986 2.83e-12 ***
# landuse_factorDeciduous                           0.277893   0.053718   5.173 2.30e-07 ***
# landuse_factorMixed                               0.056143   0.032869   1.708  0.08762 .  
# landuse_factorOpen/shrub/bog                      0.053000   0.039172   1.353  0.17605    
# landuse_factorNew forest                          0.358126   0.027347  13.096  < 2e-16 ***
# crosses_stateFALSE:factor(time_category)Night    -0.788127  15.372811  -0.051  0.95911    
# crosses_stateTRUE:factor(time_category)Night     -0.112663  15.377747  -0.007  0.99415    
# crosses_stateFALSE:factor(time_category)Twilight -0.784587  22.568458  -0.035  0.97227    
# crosses_stateTRUE:factor(time_category)Twilight   0.517331  22.574208   0.023  0.98172    
# crosses_localTRUE:factor(time_category)Night     -0.046512   0.095223  -0.488  0.62523    
# crosses_localTRUE:factor(time_category)Twilight   0.344776   0.139541   2.471  0.01348 *  

# remove 1 non-significant

TMBStruc55.1 <- glmmTMB(
  case_ ~ log_sl_ + cos_ta_ + 
    crosses_state+ crosses_local + 
    landuse_factor +
    factor(time_category):crosses_local +
    (1 | str_ID) +   
    (1 | id), 
  family = poisson,
  data = steps3,
  doFit = FALSE
)

TMBStruc55.1$parameters$theta[1] = log(1e3)  

TMBStruc55.1$mapArg = list(theta = factor(c(NA, 1)))

model_glmm55.1 <- glmmTMB:::fitTMB(TMBStruc55.1)

summary(model_glmm55.1)

#       AIC       BIC    logLik  deviance  df.resid 
#  404796.1  404950.4 -202383.0  404766.1    216421 
# 
# Random effects:
# 
# Conditional model:
#  Groups Name        Variance  Std.Dev. 
#  str_ID (Intercept) 1.000e+06 1000.0000
#  id     (Intercept) 1.733e-01    0.4163
# Number of obs: 216436, groups:  str_ID, 19676; id, 8
# 
# Conditional model:
#                                                   Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                      -2.784755  10.142974  -0.275   0.7837    
# log_sl_                                           0.146043   0.008086  18.061  < 2e-16 ***
# cos_ta_                                           0.007193   0.007519   0.957   0.3387    
# crosses_stateTRUE                                -0.506580   0.157540  -3.216   0.0013 ** 
# crosses_localTRUE                                -0.428225   0.073241  -5.847 5.01e-09 ***
# landuse_factorHuman-modified                     -0.321348   0.045714  -7.030 2.07e-12 ***
# landuse_factorDeciduous                           0.243212   0.053420   4.553 5.29e-06 ***
# landuse_factorMixed                               0.033346   0.032872   1.014   0.3104    
# landuse_factorOpen/shrub/bog                      0.046441   0.039028   1.190   0.2341    
# landuse_factorNew forest                          0.360644   0.027394  13.165  < 2e-16 ***
# crosses_localFALSE:factor(time_category)Night    -0.515498  15.372696  -0.034   0.9732    
# crosses_localTRUE:factor(time_category)Night     -0.519416  15.372969  -0.034   0.9730    
# crosses_localFALSE:factor(time_category)Twilight -0.328817  22.568371  -0.015   0.9884    
# crosses_localTRUE:factor(time_category)Twilight  -0.003266  22.568761   0.000   0.9999   






```




```{r step length ~ distance to road}

# Calculate distance to nearest road for each step
steps_with_dist <- steps3_original

# Create distance bands
steps_with_dist$dist_band <- cut(steps_with_dist$state_d, 
                                breaks = c(-Inf, 100, 300, 500, 1000, 1500, 2000, Inf),
                                labels = c("<100m", "100-300m", "300-500m", "500-1000m", "1000-1500m", "1500-2000m", ">2000m"))


# Only use used steps (case_ == TRUE)
used_steps <- steps_with_dist[steps_with_dist$case_ == TRUE,]

# Calculate mean step length by distance band
sl_by_dist <- aggregate(sl_ ~ dist_band, data = used_steps, FUN = mean)

# Visualize
ggplot(used_steps, aes(x = dist_band, y = sl_)) +
  geom_boxplot() +
  labs(x = "Distance to road, m", y = "Step length, m",
       title = "Movement speed vs distance to road")

# Statistical test
model_sl <- lm(sl_ ~ dist_band, data = used_steps)
anova(model_sl)


# Convert turning angles to absolute deviation from straight-line movement
used_steps$turn_abs <- abs(used_steps$ta_)

used_steps$turn_abs_deg <- used_steps$turn_abs * (180/pi)

# Calculate mean turning angle by distance band
ta_by_dist <- aggregate(turn_abs_deg ~ dist_band, data = used_steps, FUN = mean)

# Visualize
ggplot(used_steps, aes(x = dist_band, y = turn_abs_deg)) +
  geom_boxplot() +
  labs(x = "Distance to road, m", y = "Absolute turning angle, degrees",
       title = "Movement direction persistance vs distance to road")

# Statistical test
model_ta <- lm(turn_abs ~ dist_band, data = used_steps)
anova(model_ta)

ggplot(used_steps, aes(x = ta_ * (180/pi), fill = dist_band)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ dist_band) +
  labs(x = "Turning angle, degrees", y = "Density",
       title = "Distribution of turning Angles by distance from state road")



ggplot(used_steps, aes(x = log(sl_), fill = dist_band)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ dist_band) +
  labs(x = "Log step length, m", y = "Density",
       title = "Distribution of step length by distance from state road")



ggplot(used_steps, aes(x = log(sl_))) +
  geom_histogram(alpha = 0.5) +
  labs(x = "Step length, m", y = "Density",
       title = "Distribution of step length")



ggplot(steps3, aes(x = slope)) +
  geom_histogram(alpha = 0.5) +
  labs(x = "Slope, degrees", y = "Density")

```


# ----------------------------------------------- VISUALISATIONS ------------------------------------


```{r inspect variables}

# --- correlations ----


numeric_predictors <- steps3 %>% 
  select(sl_, ta_, local_d, slope, state_d)

correlation_matrix <- cor(numeric_predictors, use = "complete.obs")

print(correlation_matrix)

#                  sl_          ta_      local_d        slope      state_d
# sl_      1.000000000 -0.004054380 -0.010293914  0.012584876  0.005188543
# ta_     -0.004054380  1.000000000 -0.001068038 -0.001814821 -0.001102120
# local_d -0.010293914 -0.001068038  1.000000000 -0.161475131  0.069548081
# slope    0.012584876 -0.001814821 -0.161475131  1.000000000 -0.075171182
# state_d  0.005188543 -0.001102120  0.069548081 -0.075171182  1.000000000

corrplot(correlation_matrix, method = "color", type = "upper", 
         order = "hclust", tl.col = "black", tl.srt = 45,
         diag = FALSE) 



summary(aov(s_state_d ~ landuse_factor, data = steps3))
summary(aov(s_local_d ~ landuse_factor, data = steps3))
summary(aov(s_sl_ ~ landuse_factor, data = steps3))

ggplot(steps3, aes(x = landuse_factor, y = s_state_d)) +
  geom_boxplot() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Distance to state road by land use type")



# ---- distributions? ---------


ggplot(used_steps, aes(x = sl_)) +
  geom_histogram(alpha = 0.5) +
  labs(x = "Step length, m", y = "Density",
       title = "Distribution of step length")



ggplot(steps3_original, aes(x = slope)) +
  geom_histogram(alpha = 0.5) +
  labs(x = "Slope, degrees", y = "Count")

ggplot(steps3_original, aes(x = scale(sl_))) +
  geom_histogram(alpha = 0.5) +
  labs(x = "scaled Step length, m", y = "Count")

ggplot(steps3_original, aes(x = scale(state_d))) +
  geom_histogram(alpha = 0.5) +
  labs(x = "scaled Distance to state roads, m", y = "Count")

ggplot(steps3_original, aes(x = scale(local_d))) +
  geom_histogram(alpha = 0.5) +
  labs(x = "scaled Distance to local roads, m", y = "Count")

ggplot(steps3_original, aes(x = ta_)) +
  geom_histogram(alpha = 0.5) +
  labs(x = "Turning angle, radians", y = "Count")

# transformations -> what to make?

ggplot(steps3_original, aes(x = log(slope))) +
  geom_histogram(alpha = 0.5) +
  labs(x = "Slope, degrees", y = "Count")

ggplot(steps3_original, aes(x = log(sl_))) +
  geom_histogram(alpha = 0.5) +
  labs(x = "log step length, m", y = "Count")

ggplot(steps3_original, aes(x = log(state_d + 0.01))) +
  geom_histogram(alpha = 0.5) +
  labs(x = "Log distance to state roads, m + 0.01", y = "Count")

ggplot(steps3_original, aes(x = sqrt(local_d))) +
  geom_histogram(alpha = 0.5) +
  labs(x = "sqrt distance to local roads, m", y = "Count")

ggplot(steps3_original, aes(x = cos(ta_))) +
  geom_histogram(alpha = 0.5) +
  labs(x = "cos (turning angle in radians)", y = "Count")

# ---------------- crossings as not significant -----------------------
used_steps <- steps3[steps3$case_ == TRUE,]

crossing_counts_state <- table(
  Time = used_steps$time_category[used_steps$crosses_state == TRUE],
  Season = used_steps$season[used_steps$crosses_state == TRUE]
)
#           Season
# Time       Winter Summer Spring
#   Day           3      1      6
#   Night        16      7      7
#   Twilight      5      1      3

crossing_counts_local <- table(
  Time = used_steps$time_category[used_steps$crosses_local == TRUE],
  Season = used_steps$season[used_steps$crosses_local == TRUE]
)
#           Season
# Time       Winter Summer Spring
#   Day          44    136     81
#   Night       205     98     82
#   Twilight     28     55     27   


# > sum(crossing_counts_local$Freq[crossing_counts_local$Time == "Day"])
# [1] 261

rnd_steps <- steps3[steps3$case_ == FALSE,]


crossing_counts_state_rnd <- table(
  Time = rnd_steps$time_category[rnd_steps$crosses_state == TRUE],
  Season = rnd_steps$season[rnd_steps$crosses_state == TRUE]
)

#           Season
# Time       Summer Spring Winter
#   Day          89    109     36
#   Night        66     67    233
#   Twilight     22     22     40

crossing_counts_local_rnd <- table(
  Time = rnd_steps$time_category[rnd_steps$crosses_local == TRUE],
  Season = rnd_steps$season[rnd_steps$crosses_local == TRUE]
)

#           Season
# Time       Summer Spring Winter
#   Day        1687   1102    455
#   Night      1268    881   2838
#   Twilight    456    212    339


lm_model <- glm(
  num_case_ ~ s_sl_ + 
    s_state_d + s_local_d + 
    landuse_factor +
    time_category:s_state_d + time_category:s_local_d,
  family = poisson,
  data = steps3
)

# Calculate VIFs
vif_values <- vif(lm_model)
print(vif_values)

# For interaction terms, you can use:
vif_values_interactions <- vif(lm_model, type = "terms")
print(vif_values_interactions)

```




```{r mean distances descriptive}


# ----------------- mean distances to roads per category --------------------


ggplot(steps3_original %>% filter(case_ == TRUE), 
       aes(x = time_category, y = local_d)) +
  geom_boxplot() +
  labs(title = "Actual distances to local roads by time of day",
       y = "Distance (m)")


ggplot(steps3_original %>% filter(case_ == TRUE), 
       aes(x = time_category, y = state_d)) +
  geom_boxplot() +
  labs(title = "Actual distances to state roads by time of day",
       y = "Distance (m)")

# Alternative approach using data.frame subsets
day_summary <- with(subset(steps3_original, case_ == TRUE & time_category == "Day"), 
                  c(local_mean = mean(local_d, na.rm = TRUE),
                    state_mean = mean(state_d, na.rm = TRUE),
                    n = length(major_d)))

night_summary <- with(subset(steps3_original, case_ == TRUE & time_category == "Night"), 
                     c(local_mean = mean(local_d, na.rm = TRUE),
                       state_mean = mean(state_d, na.rm = TRUE),
                       n = length(major_d)))

twilight_summary <- with(subset(steps3_original, case_ == TRUE & time_category == "Twilight"), 
                        c(local_mean = mean(local_d, na.rm = TRUE),
                          state_mean = mean(state_d, na.rm = TRUE),
                          n = length(major_d)))

# Combine results
daytime_summary <- rbind(Day = day_summary, Night = night_summary, Twilight = twilight_summary)


# Alternative approach using data.frame subsets
winter_summary <- with(subset(steps3_original, case_ == TRUE & season == "Winter"), 
                  c(local_mean = mean(local_d, na.rm = TRUE),
                    state_mean = mean(state_d, na.rm = TRUE),
                    n = length(major_d)))

spring_summary <- with(subset(steps3_original, case_ == TRUE & season == "Spring"), 
                     c(local_mean = mean(local_d, na.rm = TRUE),
                       state_mean = mean(state_d, na.rm = TRUE),
                       n = length(major_d)))

summer_summary <- with(subset(steps3_original, case_ == TRUE & season == "Summer"), 
                        c(local_mean = mean(local_d, na.rm = TRUE),
                          state_mean = mean(state_d, na.rm = TRUE),
                          n = length(major_d)))

# Combine results
season_summary <- rbind(Winter = winter_summary, Spring = spring_summary, Summer = summer_summary)


# adding standard error and plotting

# We need to calculate standard errors from your original data
# For each time category (Day, Night, Twilight)
time_data <- list()

# Let's calculate means and standard errors for each time category
for (time in c("Day", "Night", "Twilight")) {
  # Subset data
  subset_data <- steps3_original[steps3_original$case_ == TRUE & 
                                steps3_original$time_category == time, ]
  
  # Calculate local road statistics
  local_mean <- mean(subset_data$local_d, na.rm = TRUE)
  local_sd <- sd(subset_data$local_d, na.rm = TRUE)
  local_n <- sum(!is.na(subset_data$local_d))
  local_se <- local_sd / sqrt(local_n)
  
  # Calculate state road statistics
  state_mean <- mean(subset_data$state_d, na.rm = TRUE)
  state_sd <- sd(subset_data$state_d, na.rm = TRUE)
  state_n <- sum(!is.na(subset_data$state_d))
  state_se <- state_sd / sqrt(state_n)
  
  time_data[[time]] <- data.frame(
    time_category = time,
    local_mean = local_mean,
    local_se = local_se,
    state_mean = state_mean, 
    state_se = state_se,
    n = local_n
  )
}

# Combine results
time_df <- do.call(rbind, time_data)

# Reshape for plotting
time_long <- reshape(time_df,
                   direction = "long",
                   varying = list(c("local_mean", "state_mean"), c("local_se", "state_se")),
                   v.names = c("mean", "se"),
                   timevar = "road_type",
                   times = c("Local roads", "State roads"))

# Plot with error bars
ggplot(time_long, aes(x = time_category, y = mean, 
                    group = road_type, color = road_type)) +
  geom_line(size = 1) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), 
               width = 0.2, position = position_dodge(0.1)) +
  scale_y_continuous(name = "Distance (m)", limits = c(0, 2500)) +
  scale_color_manual(values = c("Local roads" = "#1b9e77", "State roads" = "#7570b3"),
                    name = "Road type") +
  theme_minimal() +
  theme(
    legend.position = "right",
    axis.title.x = element_blank(),
    panel.grid.minor = element_blank(),
    text = element_text(size = 12)
  ) +
  labs(title = "Average distance to road types by time of day")

# Similarly for season plot
season_data <- list()

for (seas in c("Winter", "Spring", "Summer")) {
  # Subset data
  subset_data <- steps3_original[steps3_original$case_ == TRUE & 
                                steps3_original$season == seas, ]
  
  # Calculate local road statistics
  local_mean <- mean(subset_data$local_d, na.rm = TRUE)
  local_sd <- sd(subset_data$local_d, na.rm = TRUE)
  local_n <- sum(!is.na(subset_data$local_d))
  local_se <- local_sd / sqrt(local_n)
  
  # Calculate state road statistics
  state_mean <- mean(subset_data$state_d, na.rm = TRUE)
  state_sd <- sd(subset_data$state_d, na.rm = TRUE)
  state_n <- sum(!is.na(subset_data$state_d))
  state_se <- state_sd / sqrt(state_n)
  
  season_data[[seas]] <- data.frame(
    season = seas,
    local_mean = local_mean,
    local_se = local_se,
    state_mean = state_mean, 
    state_se = state_se,
    n = local_n
  )
}

# Combine results
season_df <- do.call(rbind, season_data)

# Reshape for plotting
season_long <- reshape(season_df,
                     direction = "long",
                     varying = list(c("local_mean", "state_mean"), c("local_se", "state_se")),
                     v.names = c("mean", "se"),
                     timevar = "road_type",
                     times = c("Local roads", "State roads"))

# Plot with error bars
ggplot(season_long, aes(x = season, y = mean, 
                       group = road_type, color = road_type)) +
  geom_line(size = 1) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), 
               width = 0.2, position = position_dodge(0.1)) +
  scale_y_continuous(name = "Distance (m)", limits = c(0, 2500)) +
  scale_color_manual(values = c("Local roads" = "#1b9e77", "State roads" = "#7570b3"),
                    name = "Road type") +
  theme_minimal() +
  theme(
    legend.position = "right",
    axis.title.x = element_blank(),
    panel.grid.minor = element_blank(),
    text = element_text(size = 12)
  ) +
  labs(title = "Average distance to road types by season")

# joined 
time_long$category_type <- "Time of day"
season_long$category_type <- "Season"

# rename to be consistent
names(time_long)[names(time_long) == "time_category"] <- "category"
names(season_long)[names(season_long) == "season"] <- "category"

#combine
all_data <- rbind(time_long, season_long)

#single plot for tidy output
ggplot(all_data, aes(x = category, y = mean, 
                    group = road_type, color = road_type)) +
  geom_line(size = 0.5) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), 
               width = 0.2) +
  facet_wrap(~ category_type, scales = "free_x") +
  scale_y_continuous(name = "Distance, m", limits = c(0, 2500)) +
  scale_color_manual(values = c("#ba936b", "#E6550D"),
    labels = c("Local road", "State road")) +
  labs(title = "Average distance to road types",
       color = "") +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    axis.title.x = element_blank(),
    panel.grid.minor = element_blank(),
    text = element_text(size = 14, family = "Times"),
    plot.title=element_text( hjust=0.5, vjust=0.5)
  )

ggsave("average_distance_to_road.png", width = 7, height = 4, bg = "white", device = png)


```






```{r log ratio plot }



# prepare data with used/available points and distance bands
points_data <- steps3_original %>%
  dplyr::select(time_category, state_d, case_) %>%
  mutate(point_type = ifelse(case_ == TRUE, "Used", "Available"))

# create distance bands from roads
points_data$dist_band <- cut(points_data$state_d, 
                             breaks = c(-Inf, 100, 300, 500, 1000, 1500, Inf),
                             labels = c("<100m", "100-300m", "300-500m", "500-1000m", "1000-1500m", ">1500m"))


# count observations in each group and calculate percentages
count_df <- as.data.frame(table(
  points_data$time_category, 
  points_data$point_type, 
  points_data$dist_band
))
names(count_df) <- c("time_category", "point_type", "dist_band", "count")


# add sample sizes to data for text annotation
used_counts <- subset(count_df, point_type == "Used")
names(used_counts)[4] <- "sample_size"

# calculate proportions and reshape
props_df <- count_df %>%
  group_by(time_category, point_type) %>%
  mutate(prop = count/sum(count)) %>%
  dplyr::select(-count) %>%
  pivot_wider(names_from = point_type, values_from = prop)

# calculate selection ratio and simple approximate CIs
ratio_df <- props_df %>%
  mutate(
    ratio = Used / Available,
    
    # Same calculations for standard errors as before
    n_used = sum(used_counts$sample_size[used_counts$time_category == time_category]),
    n_avail = n_used * 10,
    
    se_used = sqrt(Used * (1-Used) / n_used),
    se_avail = sqrt(Available * (1-Available) / n_avail),
    
    # Standard error for the ratio using delta method
    se_ratio = ratio * sqrt((se_used/Used)^2 + (se_avail/Available)^2),
    
    # 95% confidence intervals for the ratio (not the log)
    ci_lower = ratio - 1.96 * se_ratio,
    ci_upper = ratio + 1.96 * se_ratio
  )

# merge with sample sizes
ratio_df <- merge(ratio_df, 
                 used_counts[, c("time_category", "dist_band", "sample_size")],
                 by = c("time_category", "dist_band"))


ggplot(ratio_df, aes(x = dist_band, y = ratio, fill = time_category)) +
  geom_col(position = position_dodge(width = 0.9), alpha = 0.7) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                position = position_dodge(width = 0.9),
                width = 0.2) +
  geom_hline(yintercept = 1, linetype = "dashed") +  # Note: baseline is 1, not 0
  scale_fill_manual(
    values = c("#FFC145", "#2B3A67", "#B8B8D1"),
    labels = c("Day", "Night", "Twilight")
  ) +
  labs(title = "Road distance selection ratio by time of day",
       x = "Distance from state roads", 
       y = "Selection ratio (used:available)",
       fill = "Time category") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title=element_text(hjust=0.5, vjust=0.5),
        text = element_text(family = "Times", size = 14))

ggsave("distance_prop_ratio_state.png", height = 6, width = 8,  bg = "white", device = png)


# --------------------------------------------------- bins local roads ----------------


# prepare data with used/available points and distance bands
points_data <- steps3_original %>%
  dplyr::select(time_category, local_d, case_) %>%
  mutate(point_type = ifelse(case_ == TRUE, "Used", "Available"))

# create distance bands from roads
points_data$dist_band <- cut(points_data$local_d, 
                             breaks = c(-Inf, 100, 300, 500, 1000, 1500, Inf),
                             labels = c("<100m", "100-300m", "300-500m", "500-1000m", "1000-1500m", ">1500m"))


# count observations in each group and calculate percentages
count_df <- as.data.frame(table(
  points_data$time_category, 
  points_data$point_type, 
  points_data$dist_band
))
names(count_df) <- c("time_category", "point_type", "dist_band", "count")


# add sample sizes to data for text annotation
used_counts <- subset(count_df, point_type == "Used")
names(used_counts)[4] <- "sample_size"

# calculate proportions and reshape
props_df <- count_df %>%
  group_by(time_category, point_type) %>%
  mutate(prop = count/sum(count)) %>%
  dplyr::select(-count) %>%
  pivot_wider(names_from = point_type, values_from = prop)


# calculate selection ratio and simple approximate CIs
ratio_df <- props_df %>%
  mutate(
    ratio = Used / Available,
    
    # Same calculations for standard errors as before
    n_used = sum(used_counts$sample_size[used_counts$time_category == time_category]),
    n_avail = n_used * 10,
    
    se_used = sqrt(Used * (1-Used) / n_used),
    se_avail = sqrt(Available * (1-Available) / n_avail),
    
    # Standard error for the ratio using delta method
    se_ratio = ratio * sqrt((se_used/Used)^2 + (se_avail/Available)^2),
    
    # 95% confidence intervals for the ratio (not the log)
    ci_lower = ratio - 1.96 * se_ratio,
    ci_upper = ratio + 1.96 * se_ratio
  )

# merge with sample sizes
ratio_df <- merge(ratio_df, 
                 used_counts[, c("time_category", "dist_band", "sample_size")],
                 by = c("time_category", "dist_band"))


ggplot(ratio_df, aes(x = dist_band, y = ratio, fill = time_category)) +
  geom_col(position = position_dodge(width = 0.9), alpha = 0.7) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                position = position_dodge(width = 0.9),
                width = 0.2) +
  geom_hline(yintercept = 1, linetype = "dashed") +  # Note: baseline is 1, not 0
  scale_fill_manual(
    values = c("#FFC145", "#2B3A67", "#B8B8D1"),
    labels = c("Day", "Night", "Twilight")
  ) +
  labs(title = "Road distance selection ratio by time of day",
       x = "Distance from local roads", 
       y = "Selection ratio (used:available)",
       fill = "Time category") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title=element_text(hjust=0.5, vjust=0.5),
        text = element_text(family = "Times", size = 14))

ggsave("distance_prop_ratio_local.png", height = 6, width = 8,  bg = "white", device = png)




```


```{r log odds crossing counts}



# --------- log odds of crossings -----------



# 1. Create a function to calculate crossing ratios with confidence intervals
calculate_crossing_ratio <- function(data, road_type = "state") {
  # Determine which crossing variable to use
  crossing_var <- paste0("crosses_", road_type)
  
  # Count observed crossings (actual moose steps)
  observed <- data[data$case_ == TRUE, ]
  total_observed <- nrow(observed)
  observed_crossings <- sum(observed[[crossing_var]])
  observed_prop <- observed_crossings / total_observed
  
  # Count expected crossings (random steps)
  expected <- data[data$case_ == FALSE, ]
  total_expected <- nrow(expected)
  expected_crossings <- sum(expected[[crossing_var]])
  expected_prop <- expected_crossings / total_expected
  
  # Calculate ratio (accounting for 10:1 sampling of random:observed steps)
  ratio <- observed_prop / expected_prop
  
  # Calculate standard error and 95% CI for the ratio using delta method
  # For proportions: SE = sqrt(p*(1-p)/n)
  se_obs <- sqrt(observed_prop * (1 - observed_prop) / total_observed)
  se_exp <- sqrt(expected_prop * (1 - expected_prop) / total_expected)
  
  # For ratio: using approximation based on propagation of error
  # SE_ratio ≈ ratio * sqrt((SE_obs/obs_prop)^2 + (SE_exp/exp_prop)^2)
  se_ratio <- ratio * sqrt((se_obs/observed_prop)^2 + (se_exp/expected_prop)^2)
  
  # 95% confidence interval for the ratio
  ci_lower <- ratio - 1.96 * se_ratio
  ci_upper <- ratio + 1.96 * se_ratio
  
  # Return results
  result <- data.frame(
    road_type = road_type,
    observed_crossings = observed_crossings,
    expected_crossings = expected_crossings,
    observed_prop = observed_prop,
    expected_prop = expected_prop,
    ratio = ratio,
    ci_lower = ci_lower,
    ci_upper = ci_upper,
    p_value = 2 * pnorm(-abs((ratio - 1)/se_ratio)) # Two-tailed test
  )
  
  return(result)
}

state_ratio <- calculate_crossing_ratio(steps3, "state")
local_ratio <- calculate_crossing_ratio(steps3, "local")
crossing_ratios <- rbind(state_ratio, local_ratio)

# calculate crossing ratios by category
calculate_crossing_ratio_by_category <- function(data, road_type = "state", category_var = "time_category") {
  # Determine which crossing variable to use
  crossing_var <- paste0("crosses_", road_type)
  
  # Get all category levels
  categories <- unique(data[[category_var]])
  results <- data.frame()
  
  for (cat in categories) {
    # Subset data for this category
    cat_data <- data[data[[category_var]] == cat, ]
    
    # Observed crossings
    observed <- cat_data[cat_data$case_ == TRUE, ]
    total_observed <- nrow(observed)
    if (total_observed == 0) next
    observed_crossings <- sum(observed[[crossing_var]])
    observed_prop <- observed_crossings / total_observed
    
    # Expected crossings
    expected <- cat_data[cat_data$case_ == FALSE, ]
    total_expected <- nrow(expected)
    expected_crossings <- sum(expected[[crossing_var]])
    expected_prop <- expected_crossings / total_expected
    
    # Calculate ratio
    ratio <- observed_prop / expected_prop
    
    # Calculate SE and CI
    se_obs <- sqrt(observed_prop * (1 - observed_prop) / total_observed)
    se_exp <- sqrt(expected_prop * (1 - expected_prop) / total_expected)
    se_ratio <- ifelse(
      observed_prop == 0 || expected_prop == 0, 
      NA, 
      ratio * sqrt((se_obs/observed_prop)^2 + (se_exp/expected_prop)^2)
    )
    
    ci_lower <- ratio - 1.96 * se_ratio
    ci_upper <- ratio + 1.96 * se_ratio
    
    # Store results
    cat_result <- data.frame(
      road_type = road_type,
      category = cat,
      category_var = category_var,
      observed_crossings = observed_crossings,
      expected_crossings = expected_crossings,
      total_observed = total_observed,
      total_expected = total_expected,
      observed_prop = observed_prop,
      expected_prop = expected_prop,
      ratio = ratio,
      ci_lower = ci_lower,
      ci_upper = ci_upper
    )
    
    results <- rbind(results, cat_result)
  }
  
  return(results)
}

#crossing ratios by time of day
time_state_ratios <- calculate_crossing_ratio_by_category(steps3, "state", "time_category")
time_local_ratios <- calculate_crossing_ratio_by_category(steps3, "local", "time_category")
time_combined <- rbind(
  time_state_ratios %>% mutate(road_group = "State Roads"),
  time_local_ratios %>% mutate(road_group = "Local Roads")
)

#crossing ratios by season
season_state_ratios <- calculate_crossing_ratio_by_category(steps3, "state", "season")
season_local_ratios <- calculate_crossing_ratio_by_category(steps3, "local", "season")
season_combined <- rbind(
  season_state_ratios %>% mutate(road_group = "State Roads"),
  season_local_ratios %>% mutate(road_group = "Local Roads")
)

#  crossing ratio plot for road types
ggplot(crossing_ratios, aes(x = road_type, y = ratio, fill = road_type)) +
  geom_bar(stat = "identity", width = 0.6) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  labs(x = "Season", y = "Log Ratio (Used:Available)",
       title = "Road crossing avoidance by season",
       fill = "") +
  scale_fill_manual(
    values = c("#C4A484", "#C14608"),
    labels = c("Local", "State")
  ) +
    theme_minimal() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5),
        text = element_text(family = "Times"))



# plotting in one plot together

time_combined$category_type <- "Time of day"
season_combined$category_type <- "Season"
all_crossing_data <- rbind(time_combined, season_combined)

# plotting in one plot together with regular ratios
ggplot(all_crossing_data, aes(x = category, y = ratio, fill = road_group)) +
  geom_bar(stat = "identity", position = position_dodge(), width = 0.7) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                position = position_dodge(width = 0.7), width = 0.2) +
  geom_hline(yintercept = 1, linetype = "dashed") +  # Reference line at 1
  facet_wrap(~ category_type, scales = "free_x") +
  labs(x = "", y = "Selection ratio (used:available)",
       title = "Road crossing selection ratio by time of day and season",
       fill = "") +
  scale_fill_manual(
    values = c("#C4A484", "#E6550D"),
    labels = c("Local road", "State road")
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, vjust = 0.5),
    text = element_text(family = "Times", size = 14),
    legend.position = "bottom",
    panel.grid.minor = element_blank(),
    strip.text = element_text(size = 13)
  )

ggsave("crossing_ratio.png", height = 6, width = 8,  bg = "white", device = png)



```




```{r CI probabilities}

# Simplified visualization code for moose habitat selection models

# 1. Function for basic model with no interactions
calculate_basic_ci <- function(model, data, road_var, max_dist = 2000) {
  # Get scaling parameters - calculate directly
  var_center <- attr(data[[road_var]], "scaled:center")
  var_scale <- attr(data[[road_var]], "scaled:scale")
  
  # Extract coefficients and variance
  coefs <- fixef(model)$cond
  vcov_matrix <- vcov(model)$cond
  
  # Find the coefficient
  effect <- coefs[road_var]
  effect_se <- sqrt(diag(vcov_matrix)[road_var])
  
  # Create distance sequence
  dist_seq <- seq(0, max_dist, length.out = 100)
  scaled_seq <- (dist_seq - var_center) / var_scale
  
  # Calculate linear predictor and CI
  linear_pred <- scaled_seq * effect
  linear_ci_lower <- linear_pred - 1.96 * effect_se * abs(scaled_seq)
  linear_ci_upper <- linear_pred + 1.96 * effect_se * abs(scaled_seq)
  
  # Calculate RSS and probability
  rss <- exp(linear_pred)
  rss_lower <- exp(linear_ci_lower)
  rss_upper <- exp(linear_ci_upper)
  
  prob <- rss / (rss + 10)
  prob_lower <- rss_lower / (rss_lower + 10)
  prob_upper <- rss_upper / (rss_upper + 10)
  
  # Store results
  results <- data.frame(
    distance = dist_seq,
    probability = prob,
    prob_lower = prob_lower,
    prob_upper = prob_upper
  )
  
  return(results)
}

# 2. Function for time of day models
calculate_time_ci <- function(model, data, road_var, max_dist = 2000) {
  # Get scaling parameters - calculate directly
  var_center <- attr(data[[road_var]], "scaled:center")
  var_scale <- attr(data[[road_var]], "scaled:scale")
  
  # Extract coefficients and variance-covariance matrix
  coefs <- fixef(model)$cond
  vcov_matrix <- vcov(model)$cond
  
  # Create distance sequence
  dist_seq <- seq(0, max_dist, length.out = 100)
  scaled_seq <- (dist_seq - var_center) / var_scale
  
  # For each time category
  time_cats <- c("Day", "Night", "Twilight")
  all_predictions <- data.frame()
  
  for (time_cat in time_cats) {
    # Calculate effect and SE for this time category
    if (time_cat == "Day") {
      effect <- coefs[road_var]
      effect_se <- sqrt(diag(vcov_matrix)[road_var])
    } else {
      # The interaction term uses time_category (not factor(time_category))
      interaction_name <- paste0(road_var, ":time_category", time_cat)
      
      effect <- coefs[road_var] + coefs[interaction_name]
      
      # Calculate standard error for combined effect
      main_se <- sqrt(diag(vcov_matrix)[road_var])
      int_se <- sqrt(diag(vcov_matrix)[interaction_name])
      covar <- vcov_matrix[road_var, interaction_name]
      effect_se <- sqrt(main_se^2 + int_se^2 + 2*covar)
    }
    
    # Calculate linear predictor, selection strength, and probability
    linear_pred <- scaled_seq * effect
    linear_ci_lower <- linear_pred - 1.96 * effect_se * abs(scaled_seq)
    linear_ci_upper <- linear_pred + 1.96 * effect_se * abs(scaled_seq)
    
    # Calculate RSS and probability
    rss <- exp(linear_pred)
    rss_lower <- exp(linear_ci_lower)
    rss_upper <- exp(linear_ci_upper)
    
    prob <- rss / (rss + 10)
    prob_lower <- rss_lower / (rss_lower + 10)
    prob_upper <- rss_upper / (rss_upper + 10)
    
    # Store results
    time_results <- data.frame(
      distance = dist_seq,
      probability = prob,
      prob_lower = prob_lower,
      prob_upper = prob_upper,
      time_category = time_cat,
      road_var = road_var
    )
    
    all_predictions <- rbind(all_predictions, time_results)
  }
  
  return(all_predictions)
}

# 3. Function for seasonal models
calculate_season_ci <- function(model, data, road_var, max_dist = 2000) {
  # Get scaling parameters - calculate directly
  var_center <- attr(data[[road_var]], "scaled:center")
  var_scale <- attr(data[[road_var]], "scaled:scale")
  
  # Extract coefficients and variance-covariance matrix
  coefs <- fixef(model)$cond
  vcov_matrix <- vcov(model)$cond
  
  # Create distance sequence
  dist_seq <- seq(0, max_dist, length.out = 100)
  scaled_seq <- (dist_seq - var_center) / var_scale
  
  # Define season categories
  season_cats <- levels(data$season)
  all_predictions <- data.frame()
  
  # For each season
  for (season_cat in season_cats) {
    # Calculate effect and SE for this season
    if (season_cat == "Winter") {  # Winter is the reference level
      effect <- coefs[road_var]
      effect_se <- sqrt(diag(vcov_matrix)[road_var])
    } else {
      # Get the interaction term
      interaction_name <- paste0(road_var, ":season", season_cat)
      
      # Calculate the combined effect
      effect <- coefs[road_var] + coefs[interaction_name]
      
      # Calculate standard error for combined effect
      main_se <- sqrt(diag(vcov_matrix)[road_var])
      int_se <- sqrt(diag(vcov_matrix)[interaction_name])
      covar <- vcov_matrix[road_var, interaction_name]
      effect_se <- sqrt(main_se^2 + int_se^2 + 2*covar)
    }
    
    # Calculate linear predictor and CIs
    linear_pred <- scaled_seq * effect
    linear_ci_lower <- linear_pred - 1.96 * effect_se * abs(scaled_seq)
    linear_ci_upper <- linear_pred + 1.96 * effect_se * abs(scaled_seq)
    
    # Calculate RSS and probability
    rss <- exp(linear_pred)
    rss_lower <- exp(linear_ci_lower)
    rss_upper <- exp(linear_ci_upper)
    
    prob <- rss / (rss + 10)
    prob_lower <- rss_lower / (rss_lower + 10)
    prob_upper <- rss_upper / (rss_upper + 10)
    
    # Store results
    season_results <- data.frame(
      distance = dist_seq,
      probability = prob,
      prob_lower = prob_lower,
      prob_upper = prob_upper,
      season = season_cat
    )
    
    all_predictions <- rbind(all_predictions, season_results)
  }
  
  return(all_predictions)
}

# 4. Function for landuse interaction models
calculate_landuse_ci <- function(model, data, road_var, max_dist = 2000) {
  # Get scaling parameters - calculate directly
  var_center <- attr(data[[road_var]], "scaled:center")
  var_scale <- attr(data[[road_var]], "scaled:scale")
  
  # Extract coefficients and variance-covariance matrix
  coefs <- fixef(model)$cond
  vcov_matrix <- vcov(model)$cond
  
  # Create distance sequence
  dist_seq <- seq(0, max_dist, length.out = 100)
  scaled_seq <- (dist_seq - var_center) / var_scale
  
  # Define landuse categories (using actual factor levels)
  landuse_cats <- levels(data$landuse_factor)
  all_predictions <- data.frame()
  
  # Coniferous is always the reference level
  ref_level <- "Coniferous" 
  
  # For each landuse category
  for (landuse_cat in landuse_cats) {
    # Calculate effect and SE for this landuse type
    if (landuse_cat == ref_level) {
      effect <- coefs[road_var]
      effect_se <- sqrt(diag(vcov_matrix)[road_var])
    } else {
      # Get the correct interaction term name
      interaction_name <- paste0(road_var, ":landuse_factor", landuse_cat)
      
      # Calculate the combined effect (if interaction exists)
      if (interaction_name %in% names(coefs)) {
        effect <- coefs[road_var] + coefs[interaction_name]
        
        # Calculate standard error for combined effect
        main_se <- sqrt(diag(vcov_matrix)[road_var])
        int_se <- sqrt(diag(vcov_matrix)[interaction_name])
        covar <- vcov_matrix[road_var, interaction_name]
        effect_se <- sqrt(main_se^2 + int_se^2 + 2*covar)
      } else {
        # If no interaction, use base effect
        effect <- coefs[road_var]
        effect_se <- sqrt(diag(vcov_matrix)[road_var])
      }
    }
    
    # Calculate linear predictor and CIs
    linear_pred <- scaled_seq * effect
    linear_ci_lower <- linear_pred - 1.96 * effect_se * abs(scaled_seq)
    linear_ci_upper <- linear_pred + 1.96 * effect_se * abs(scaled_seq)
    
    # Calculate RSS and probability
    rss <- exp(linear_pred)
    rss_lower <- exp(linear_ci_lower)
    rss_upper <- exp(linear_ci_upper)
    
    prob <- rss / (rss + 10)
    prob_lower <- rss_lower / (rss_lower + 10)
    prob_upper <- rss_upper / (rss_upper + 10)
    
    # Store results
    landuse_results <- data.frame(
      distance = dist_seq,
      probability = prob,
      prob_lower = prob_lower,
      prob_upper = prob_upper,
      landuse = landuse_cat
    )
    
    all_predictions <- rbind(all_predictions, landuse_results)
  }
  
  return(all_predictions)
}

# Plotting functions - unchanged from original

# Plot function for basic model
plot_basic <- function(predictions, road_var = "state_d") {
  road_label <- ifelse(grepl("state", road_var), "state roads", "local roads")
  
  ggplot(predictions, aes(x = distance, y = probability)) +
    geom_ribbon(aes(ymin = prob_lower, ymax = prob_upper), 
                alpha = 0.3, fill = "#1976D2") +
    geom_line(size = 1.2, color = "#1976D2") +
    geom_hline(yintercept = 1/11, linetype = "dashed", color = "gray50") +
    labs(x = paste0("Distance to ", road_label, ", m"),
         y = "Selection probability",
         title = paste0("Moose selection probability vs. distance from ", road_label)) +
    theme_minimal() +
    theme(
      text = element_text(family = "Times", size = 14),
      panel.grid.minor = element_blank()
    )
}


# Plot function for time of day
plot_time_facet <- function(predictions, road_type = "state") {
  road_label <- ifelse(grepl("state", road_type), "state roads", "local roads")
  time_colors <- c("Day" = "#FFC145", "Night" = "#2B3A67", "Twilight" = "#B8B8D1")
  
  ggplot(predictions, aes(x = distance, y = probability, color = time_category)) +
    geom_ribbon(aes(ymin = prob_lower, ymax = prob_upper, fill = time_category), 
                alpha = 0.3, color = NA) +
    geom_line(size = 1.2) +
    geom_hline(yintercept = 1/11, linetype = "dashed", color = "gray50") +
    facet_wrap(~ time_category, nrow = 1) +
    labs(x = paste0("Distance to ", road_label, ", m"),
         y = "Selection probability",
         title = paste0("Moose selection probability vs. distance from ", road_label)) +
    theme_minimal() +
    theme(
      text = element_text(family = "Times", size = 14),
      legend.position = "none",
      panel.grid.minor = element_blank(),
      strip.text = element_text(size = 12)
    ) +
    scale_color_manual(values = time_colors) +
    scale_fill_manual(values = time_colors)
}

# Plot function for seasonal model
plot_season_facet <- function(predictions, road_var = "state_d") {
  road_label <- ifelse(grepl("state", road_var), "state roads", "local roads")
  season_colors <- c("Winter" = "#8FBCE6", "Spring" = "#EBA0C6", "Summer" = "#80CFA9")
  
  ggplot(predictions, aes(x = distance, y = probability, color = season)) +
    geom_ribbon(aes(ymin = prob_lower, ymax = prob_upper, fill = season), 
                alpha = 0.3, color = NA) +
    geom_line(size = 1.2) +
    geom_hline(yintercept = 1/11, linetype = "dashed", color = "gray50") +
    facet_wrap(~ season, nrow = 1) +
    labs(x = paste0("Distance to ", road_label, ", m"),
         y = "Selection probability",
         title = paste0("Moose selection probability vs. distance from ", road_label)) +
    theme_minimal() +
    theme(
      text = element_text(family = "Times", size = 14),
      legend.position = "none",
      panel.grid.minor = element_blank(),
      strip.text = element_text(size = 12)
    ) +
    scale_color_manual(values = season_colors) +
    scale_fill_manual(values = season_colors)
}

# Plot function for landuse model
plot_landuse_facet <- function(predictions, road_var = "state_d") {
  road_label <- ifelse(grepl("state", road_var), "state roads", "local roads")
  
  # Define colors for different landuse types
  landuse_colors <- c(
    "Coniferous" = "#00A600",
    "Mixed" = "#4DFF00",
    "Deciduous" = "#80ff00",
    "Open/shrub/bog" = "#d8ec00",
    "New forest" = "#A8E4A0",
    "Human-modified" = "#E57373"
  )
  
  ggplot(predictions, aes(x = distance, y = probability, color = landuse)) +
    geom_ribbon(aes(ymin = prob_lower, ymax = prob_upper, fill = landuse), 
                alpha = 0.2, color = NA) +
    geom_line(size = 1.2) +
    geom_hline(yintercept = 1/11, linetype = "dashed", color = "gray50") +
    facet_wrap(~ landuse, nrow = 2) +
    labs(x = paste0("Distance to ", road_label, ", m"),
         y = "Selection probability",
         title = paste0("Moose selection probability vs. distance from ", road_label)) +
    theme_minimal() +
    theme(
      text = element_text(family = "Times", size = 14),
      legend.position = "none",
      panel.grid.minor = element_blank(),
      strip.text = element_text(size = 10)
    ) +
    scale_color_manual(values = landuse_colors) +
    scale_fill_manual(values = landuse_colors)
}

# Example usage for each model type:
# 
# 
# # 1. Time of Day effect
# state_time_preds <- calculate_time_ci(model_glmm3_3.0.2, steps3, "s_state_d")
# state_time_plot <- plot_time_facet(state_time_preds, "state")
# print(state_time_plot)
# 
# ggsave("state_tine_probability.png", width = 10, height = 5, bg = "white", device = png)
# 
# local_time_preds <- calculate_time_ci(model_glmm3_3.0.2, steps3, "s_local_d")
# local_time_plot <- plot_time_facet(local_time_preds, "local")
# print(local_time_plot)
# 
# ggsave("local_tine_probability.png", width = 10, height = 5, bg = "white", device = png)
# 
# # 2. Seasonal effect
# # state_season_preds <- calculate_season_ci(model_glmm2.2, steps3, "s_state_d")
# # state_season_plot <- plot_season_facet(state_season_preds, "state_d")
# # print(state_season_plot)
# # 
# ggsave("state_season_probability.png", width = 10, height = 5, bg = "white", device = png)
# 
local_season_preds <- calculate_season_ci(model_glmm2.3, steps3, "s_local_d")
local_season_plot <- plot_season_facet(local_season_preds, "local_d")
print(local_season_plot)
# 
# ggsave("local_season_probability.png", width = 10, height = 5, bg = "white", device = png)
# 
# # 3. Landuse interaction
# state_landuse_preds <- calculate_landuse_ci(model_glmm_state.2, steps3, "s_state_d")
# state_landuse_plot <- plot_landuse_facet(state_landuse_preds, "state_d")
# print(state_landuse_plot)
# 
# ggsave("state_landsue_probability.png", width = 10, height = 6, bg = "white", device = png)
# 
# local_landuse_preds <- calculate_landuse_ci(model_glmm_local.2, steps3, "s_local_d")
# local_landuse_plot <- plot_landuse_facet(local_landuse_preds, "local_d")
# print(local_landuse_plot)
# 
# ggsave("local_landuse_probability.png", width = 10, height = 5, bg = "white", device = png)
# 
# # 4. Basic road effect
# state_basic_preds <- calculate_basic_ci(model_glmm1.1.1, steps3, "s_state_d")
# state_basic_plot <- plot_basic(state_basic_preds, "state_d")
# print(state_basic_plot)
# 
# ggsave("state_basic_probability.png", width = 6, height = 4, bg = "white", device = png)
# 
# 
# local_basic_preds <- calculate_basic_ci(model_glmm1.1.1, steps3, "s_local_d")
# local_basic_plot <- plot_basic(local_basic_preds, "local_d")
# print(local_basic_plot)
# 
# ggsave("local_basic_probability.png", width = 6, height = 4, bg = "white", device = png)

# ------------ new full models ------------


basic_model <- all_model_results$basic$final_model

state_basic_preds <- calculate_basic_ci(basic_model, steps3, "s_state_d")
state_basic_plot <- plot_basic(state_basic_preds, "s_state_d")
print(state_basic_plot)

time_model <- all_model_results$time$final_model

state_time_preds <- calculate_time_ci(time_model, steps3, "s_state_d")
state_time_plot <- plot_time_facet(state_time_preds, "s_state")
print(state_time_plot)

local_time_preds <- calculate_time_ci(time_model, steps3, "s_local_d")
local_time_plot <- plot_time_facet(local_time_preds, "local")
print(local_time_plot)

season_model <- all_model_results_season$final_model

local_season_preds <- calculate_season_ci(season_model, steps3, "s_local_d")
local_season_plot <- plot_season_facet(local_season_preds, "local_d")
print(local_season_plot)



```



```{r numbers for thesis}

find_rss_threshold_distance <- function(model, data, road_var, threshold = 2.0, time_category = NULL, landuse = NULL, max_search_dist = 4000) {
  # Get scaling parameters
  var_center <- attr(data[[road_var]], "scaled:center")
  var_scale <- attr(data[[road_var]], "scaled:scale")
  
  # Extract coefficients
  coefs <- fixef(model)$cond
  
  # Function to calculate RSS at a given distance
  calculate_rss <- function(dist) {
    scaled_dist <- (dist - var_center) / var_scale
    
    # Base effect
    effect <- coefs[road_var]
    
    # Add time of day interaction if specified
    if (!is.null(time_category) && time_category != "Day") {
      interaction_name <- paste0(road_var, ":time_category", time_category)
      if (interaction_name %in% names(coefs)) {
        effect <- effect + coefs[interaction_name]
      }
    }
    
    # Add landuse interaction if specified
    if (!is.null(landuse) && landuse != "Coniferous") {
      interaction_name <- paste0(road_var, ":landuse_factor", landuse)
      if (interaction_name %in% names(coefs)) {
        effect <- effect + coefs[interaction_name]
      }
    }
    
    # Calculate RSS for this distance vs. zero distance
    scaled_zero <- (0 - var_center) / var_scale
    rss <- exp(effect * (scaled_dist - scaled_zero))
    
    return(rss - threshold) # Return difference from threshold for root-finding
  }
  
  # Use root-finding to locate the distance where RSS = threshold
  # Starting from 1 to avoid potential issues at distance = 0
  result <- try(uniroot(calculate_rss, c(1, max_search_dist)))
  
  if (class(result) == "try-error") {
    # Threshold might not be reached within range
    return(NA)
  } else {
    return(result$root)
  }
}



find_rss_threshold_distance(model_glmm3_3.0.2, steps3, "s_state_d", threshold = 2.0, time_category = "Day")
# > find_rss_threshold_distance(model_glmm3_3.0.2, steps3, "s_state_d", threshold = 2.0, time_category = "Day")
# [1] 3176.482
# > find_rss_threshold_distance(model_glmm3_3.0.2, steps3, "s_local_d", threshold = 2.0)
# [1] 1174.474
find_rss_threshold_distance(model_glmm1.1.1, steps3, "s_state_d", threshold = 2.0)
# [1] 2036.214
find_rss_threshold_distance(model_glmm1.1.1, steps3, "s_local_d", threshold = 2.0)
# [1] 2542.993

calculate_exact_rss <- function(model, data, road_var, distance, ref_distance = 0, 
                               time_category = NULL, landuse = NULL) {
  # Get scaling parameters
  var_center <- attr(data[[road_var]], "scaled:center")
  var_scale <- attr(data[[road_var]], "scaled:scale")
  
  # Calculate scaled distances
  scaled_dist <- (distance - var_center) / var_scale
  scaled_ref <- (ref_distance - var_center) / var_scale
  
  # Extract coefficients
  coefs <- fixef(model)$cond
  
  # Base effect
  effect <- coefs[road_var]
  
  # Add time of day interaction if specified
  if (!is.null(time_category) && time_category != "Day") {
    interaction_name <- paste0(road_var, ":time_category", time_category)
    if (interaction_name %in% names(coefs)) {
      effect <- effect + coefs[interaction_name]
    }
  }
  
  # Add landuse interaction if specified
  if (!is.null(landuse) && landuse != "Coniferous") {
    interaction_name <- paste0(road_var, ":landuse_factor", landuse)
    if (interaction_name %in% names(coefs)) {
      effect <- effect + coefs[interaction_name]
    }
  }
  
    # Add season interaction if specified
  if (!is.null(season) && season != "Winter") {
    interaction_name <- paste0(road_var, ":season", season)
    if (interaction_name %in% names(coefs)) {
      effect <- effect + coefs[interaction_name]
    }
  }
  
  # Calculate RSS between the two distances
  rss <- exp(effect * (scaled_dist - scaled_ref))
  
  return(rss)
}


calculate_exact_rss(model_glmm1.1.1, steps3, "s_state_d", 500)
calculate_exact_rss(model_glmm1.1.1, steps3, "s_state_d", 2000)


calculate_exact_rss(model_glmm3_3.0.2, steps3, "s_state_d", 2000, time_category = "Night")

calculate_exact_rss(model_glmm_state.2, steps3, "s_state_d", 2000, landuse = "Mixed")

calculate_exact_rss(model_glmm_local.2, steps3, "s_local_d", 500, landuse = "Mixed")


```
```{r find barrier effect distance}
find_preference_threshold_distance <- function(model, data, road_var, season = NULL, 
                                              time_category = NULL, landuse = NULL, 
                                              max_search_dist = 2000) {
  # Get scaling parameters
  var_center <- attr(data[[road_var]], "scaled:center")
  var_scale <- attr(data[[road_var]], "scaled:scale")
  
  # Extract coefficients
  coefs <- fixef(model)$cond
  
  # Function to calculate probability at a given distance
  calculate_prob <- function(dist) {
    scaled_dist <- (dist - var_center) / var_scale
    
    # Base effect
    effect <- coefs[road_var]
    
    # Add season interaction if specified
    if (!is.null(season) && season != "Winter") {
      interaction_name <- paste0(road_var, ":season", season)
      if (interaction_name %in% names(coefs)) {
        effect <- effect + coefs[interaction_name]
      }
    }
    
    # Add time of day interaction if specified
    if (!is.null(time_category) && time_category != "Day") {
      interaction_name <- paste0(road_var, ":time_category", time_category)
      if (interaction_name %in% names(coefs)) {
        effect <- effect + coefs[interaction_name]
      }
    }
    
    # Add landuse interaction if specified
    if (!is.null(landuse) && landuse != "Coniferous") {
      interaction_name <- paste0(road_var, ":landuse_factor", landuse)
      if (interaction_name %in% names(coefs)) {
        effect <- effect + coefs[interaction_name]
      }
    }
    
    # Calculate linear predictor, RSS and probability
    linear_pred <- scaled_dist * effect
    rss <- exp(linear_pred)
    prob <- rss / (rss + 10)
    
    return(prob - 1/11) # Return difference from threshold for root-finding
  }
  
  # Use root-finding to locate the distance where probability = 1/11
  result <- try(uniroot(calculate_prob, c(0, max_search_dist)))
  
  if (class(result) == "try-error") {
    # Check if we're always above or below threshold
    if (calculate_prob(0) > 0 && calculate_prob(max_search_dist) > 0) {
      return("Always preferred")
    } else if (calculate_prob(0) < 0 && calculate_prob(max_search_dist) < 0) {
      return("Always avoided")
    } else {
      return(NA)
    }
  } else {
    return(result$root)
  }
}

night_threshold <- find_preference_threshold_distance(
  all_model_results$basic$final_model, steps3, "s_local_d"
)
night_threshold




# For basic model
basic_effect <- fixef(all_model_results$basic$final_model)$cond["s_local_d"]
print(basic_effect)  # Should be 0.07625

# For time model with Night
time_model_coefs <- fixef(all_model_results$time$final_model)$cond
day_effect <- time_model_coefs["s_local_d"]  # Should be 0.16135
day_effect
night_interaction <- time_model_coefs["s_local_d:time_categoryNight"]  # Should be -0.22516
night_interaction
night_effect <- day_effect + night_interaction  # Should be -0.06381
print(night_effect)












# Simplified version for debugging
debug_preference_threshold <- function(model, variable, time_cat = NULL) {
  coefs <- fixef(model)$cond
  
  # Base effect
  effect <- coefs[variable]
  
  # Add time interaction if specified
  if (!is.null(time_cat) && time_cat != "Day") {
    interaction_name <- paste0(variable, ":time_category", time_cat)
    if (interaction_name %in% names(coefs)) {
      effect <- effect + coefs[interaction_name]
      print(paste("Adding interaction:", interaction_name, "=", coefs[interaction_name]))
    }
  }
  
  print(paste("Final effect coefficient:", effect))
  
  # Just to illustrate threshold calculation
  var_center <- attr(steps3[[variable]], "scaled:center")
  var_scale <- attr(steps3[[variable]], "scaled:scale")
  
  # Function that would be used in uniroot
  calculate_prob <- function(dist) {
    scaled_dist <- (dist - var_center) / var_scale
    linear_pred <- scaled_dist * effect
    rss <- exp(linear_pred)
    prob <- rss / (rss + 10)
    return(prob - 1/11)
  }
  
  # Test a few distances
  for (d in c(0, 200, 400, 600, 800, 1000)) {
    print(paste("Distance:", d, "Prob diff from threshold:", calculate_prob(d)))
  }
}

# Test basic model
print("BASIC MODEL")
debug_preference_threshold(all_model_results$basic$final_model, "s_local_d")

# Test time model with Night
print("TIME MODEL - NIGHT")
debug_preference_threshold(all_model_results$time$final_model, "s_local_d", "Night")

```

